import { Branch, Company } from './businesses.model';

export const COMPANIES: readonly Company[] = [
  {
    id: 'c-copacabana',
    slug: 'pollos-copacabana',
    name: 'Pollos Copacabana',
    type: 'restaurante',
    summary: 'Pollo broaster, salteñas y sopas de olla desde 1978.',
    categories: ['Combos', 'Pollo', 'Salteñas', 'Bebidas'],
    tags: ['Pollo', 'Boliviana'],
    since: '1978',
    plan: 'marca',
  },
  {
    id: 'c-oriental',
    slug: 'sabor-oriental',
    name: 'Sabor Oriental',
    type: 'restaurante',
    summary: 'Majadito, keperí y cuñapé recién horneado.',
    categories: ['Platos', 'Horneados', 'Bebidas'],
    tags: ['Camba', 'Boliviana'],
    since: '1996',
    plan: 'plus',
  },
  {
    id: 'c-illimani',
    slug: 'sushi-illimani',
    name: 'Sushi Illimani',
    type: 'restaurante',
    summary: 'Rolls de autor con trucha del Titicaca.',
    categories: ['Rolls', 'Entradas', 'Bebidas'],
    tags: ['Japonesa', 'Trucha'],
    since: '2014',
    plan: 'basico',
  },
  {
    id: 'c-cafe-sucre',
    slug: 'cafe-sucre',
    name: 'Café Sucre',
    type: 'restaurante',
    summary: 'Desayunos, tortas y café de yungas tostado en casa.',
    categories: ['Desayunos', 'Tortas', 'Café'],
    tags: ['Café', 'Repostería'],
    since: '2009',
    plan: 'basico',
  },
  {
    id: 'c-ale',
    card: { brand: 'Mastercard', last4: '8820', holder: 'Importadora Ale SRL', expires: '04/30' },
    slug: 'importadora-ale',
    name: 'Importadora Ale',
    type: 'importadora',
    summary: 'Ropa, calzado y accesorios traídos por temporada.',
    categories: ['Ropa', 'Calzado', 'Accesorios'],
    tags: ['Temporada', 'Mayor y menor'],
    since: '2011',
    plan: 'plus',
  },
  {
    id: 'c-andes',
    slug: 'andes-import',
    name: 'Andes Import',
    type: 'importadora',
    summary: 'Herramienta, ferretería y repuesto de moto.',
    categories: ['Herramienta', 'Ferretería', 'Repuestos'],
    tags: ['Taller', 'Moto'],
    since: '2007',
    plan: 'basico',
  },
  {
    id: 'c-tecno',
    slug: 'tecno-bolivia',
    name: 'Tecno Bolivia',
    type: 'importadora',
    summary: 'Celulares, audio y accesorios con garantía escrita.',
    categories: ['Celulares', 'Audio', 'Accesorios'],
    tags: ['Garantía', 'Tecnología'],
    since: '2016',
    plan: 'basico',
  },
  {
    id: 'c-yungas',
    slug: 'casa-yungas',
    name: 'Casa Yungas',
    type: 'importadora',
    summary: 'Menaje, textil de hogar y línea blanca chica.',
    categories: ['Menaje', 'Textil', 'Hogar'],
    tags: ['Hogar', 'Cocina'],
    since: '2013',
    plan: 'basico',
  },
];

const WEEKDAYS = { days: 'Lunes a viernes', opens: '08:30', closes: '20:00' };
const SATURDAY = { days: 'Sábado', opens: '09:00', closes: '18:00' };
const KITCHEN = { days: 'Lunes a domingo', opens: '11:00', closes: '22:30' };

export const BRANCHES: readonly Branch[] = [
  {
    id: 'b-copacabana-miraflores',
    slug: 'miraflores',
    companyId: 'c-copacabana',
    name: 'Copacabana Miraflores',
    cityId: 'la-paz',
    zone: 'Miraflores',
    address: 'Av. Busch 1420',
    phone: '2 224 8810',
    point: { x: 34, y: 41 },
    hours: [KITCHEN],
    open: true,
    prepMinutes: 25,
    deliveryBob: 8,
    featuredUntil: '2026-09-30',
    managerName: 'Delia Mamani',
  },
  {
    id: 'b-copacabana-sopocachi',
    slug: 'sopocachi',
    companyId: 'c-copacabana',
    name: 'Copacabana Sopocachi',
    cityId: 'la-paz',
    zone: 'Sopocachi',
    address: 'Av. 20 de Octubre 2155',
    phone: '2 241 3307',
    point: { x: 27, y: 52 },
    hours: [KITCHEN],
    open: true,
    prepMinutes: 30,
    deliveryBob: 8,
    featuredUntil: '2026-09-30',
    managerName: 'Freddy Ticona',
  },
  {
    id: 'b-copacabana-cala-cala',
    slug: 'cala-cala',
    companyId: 'c-copacabana',
    name: 'Copacabana Cala Cala',
    cityId: 'cochabamba',
    zone: 'Cala Cala',
    address: 'Av. América 780',
    phone: '4 428 9004',
    point: { x: 46, y: 33 },
    hours: [KITCHEN],
    open: false,
    prepMinutes: 25,
    deliveryBob: 7,
    managerName: 'Lucía Vargas',
  },
  {
    id: 'b-oriental-equipetrol',
    slug: 'equipetrol',
    companyId: 'c-oriental',
    name: 'Sabor Oriental Equipetrol',
    cityId: 'santa-cruz',
    zone: 'Equipetrol',
    address: 'Calle Los Cusis 240',
    phone: '3 341 7720',
    point: { x: 52, y: 46 },
    hours: [KITCHEN],
    open: true,
    prepMinutes: 30,
    deliveryBob: 10,
    managerName: 'Rubén Áñez',
  },
  {
    id: 'b-oriental-norte',
    slug: 'norte',
    companyId: 'c-oriental',
    name: 'Sabor Oriental Norte',
    cityId: 'santa-cruz',
    zone: 'Norte',
    address: 'Av. Banzer km 6',
    phone: '3 346 1188',
    point: { x: 58, y: 27 },
    hours: [KITCHEN],
    open: true,
    prepMinutes: 35,
    deliveryBob: 12,
    managerName: 'Karen Suárez',
  },
  {
    id: 'b-illimani-san-miguel',
    slug: 'san-miguel',
    companyId: 'c-illimani',
    name: 'Sushi Illimani San Miguel',
    cityId: 'la-paz',
    zone: 'San Miguel',
    address: 'Calle 21 de Calacoto 8300',
    phone: '2 279 5561',
    point: { x: 22, y: 68 },
    hours: [KITCHEN],
    open: true,
    prepMinutes: 35,
    deliveryBob: 12,
    managerName: 'Andrés Choque',
  },
  {
    id: 'b-cafe-sucre-centro',
    slug: 'centro',
    companyId: 'c-cafe-sucre',
    name: 'Café Sucre Centro',
    cityId: 'sucre',
    zone: 'Centro',
    address: 'Calle Bolívar 132',
    phone: '4 645 2210',
    point: { x: 49, y: 51 },
    hours: [{ days: 'Lunes a domingo', opens: '07:00', closes: '21:00' }],
    open: true,
    prepMinutes: 20,
    deliveryBob: 6,
    managerName: 'Nayra Calvimontes',
  },
  {
    id: 'b-cafe-sucre-recoleta',
    slug: 'recoleta',
    companyId: 'c-cafe-sucre',
    name: 'Café Sucre Recoleta',
    cityId: 'sucre',
    zone: 'Recoleta',
    address: 'Plaza Pedro de Anzúrez 4',
    phone: '4 645 8873',
    point: { x: 55, y: 63 },
    hours: [{ days: 'Lunes a domingo', opens: '08:00', closes: '20:00' }],
    open: true,
    prepMinutes: 20,
    deliveryBob: 6,
    managerName: 'Tomás Arancibia',
  },
  {
    id: 'b-ale-la-paz',
    card: { brand: 'Mastercard', last4: '8820', holder: 'Importadora Ale SRL', expires: '04/30' },
    slug: 'la-paz',
    companyId: 'c-ale',
    name: 'Ale La Paz',
    cityId: 'la-paz',
    zone: 'Centro',
    address: 'Av. Buenos Aires 1290',
    phone: '2 245 6612',
    point: { x: 30, y: 36 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 60,
    deliveryBob: 10,
    featuredUntil: '2026-09-30',
    managerName: 'Ale Quisbert',
  },
  {
    id: 'b-ale-santa-cruz',
    slug: 'santa-cruz',
    companyId: 'c-ale',
    name: 'Ale Santa Cruz',
    cityId: 'santa-cruz',
    zone: 'Centro',
    address: 'Calle Ayacucho 415',
    phone: '3 333 9042',
    point: { x: 47, y: 55 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 60,
    deliveryBob: 12,
    managerName: 'Elena Rojas',
  },
  {
    id: 'b-ale-cochabamba',
    slug: 'cochabamba',
    companyId: 'c-ale',
    name: 'Ale Cochabamba',
    cityId: 'cochabamba',
    zone: 'Centro',
    address: 'Av. Ayacucho 566',
    phone: '4 452 3391',
    point: { x: 40, y: 48 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 60,
    deliveryBob: 10,
    managerName: 'Mauricio Peña',
  },
  {
    id: 'b-andes-santa-cruz',
    slug: 'santa-cruz',
    companyId: 'c-andes',
    name: 'Andes Santa Cruz',
    cityId: 'santa-cruz',
    zone: 'Plan Tres Mil',
    address: 'Av. Paurito 1105',
    phone: '3 348 2214',
    point: { x: 63, y: 71 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 90,
    deliveryBob: 12,
    managerName: 'Willy Justiniano',
  },
  {
    id: 'b-andes-la-paz',
    slug: 'la-paz',
    companyId: 'c-andes',
    name: 'Andes La Paz',
    cityId: 'la-paz',
    zone: 'Centro',
    address: 'Calle Graneros 340',
    phone: '2 228 7715',
    point: { x: 31, y: 30 },
    hours: [WEEKDAYS],
    open: true,
    prepMinutes: 90,
    deliveryBob: 10,
    managerName: 'Sonia Apaza',
  },
  {
    id: 'b-andes-sucre',
    slug: 'sucre',
    companyId: 'c-andes',
    name: 'Andes Sucre',
    cityId: 'sucre',
    zone: 'Centro',
    address: 'Calle Junín 88',
    phone: '4 644 1907',
    point: { x: 44, y: 44 },
    hours: [WEEKDAYS],
    open: true,
    prepMinutes: 90,
    deliveryBob: 9,
    managerName: 'Iván Zamora',
  },
  {
    id: 'b-tecno-cochabamba',
    slug: 'cochabamba',
    companyId: 'c-tecno',
    name: 'Tecno Cochabamba',
    cityId: 'cochabamba',
    zone: 'Centro',
    address: 'Av. Heroínas 455',
    phone: '4 425 6600',
    point: { x: 43, y: 52 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 45,
    deliveryBob: 10,
    managerName: 'Pablo Céspedes',
  },
  {
    id: 'b-tecno-la-paz',
    slug: 'la-paz',
    companyId: 'c-tecno',
    name: 'Tecno La Paz',
    cityId: 'la-paz',
    zone: 'Centro',
    address: 'Calle Comercio 1022',
    phone: '2 231 4478',
    point: { x: 33, y: 34 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 45,
    deliveryBob: 10,
    managerName: 'Gabriela Nina',
  },
  {
    id: 'b-yungas-oruro',
    slug: 'oruro',
    companyId: 'c-yungas',
    name: 'Casa Yungas Oruro',
    cityId: 'oruro',
    zone: 'Centro',
    address: 'Calle Bolívar 620',
    phone: '2 525 3318',
    point: { x: 51, y: 39 },
    hours: [WEEKDAYS, SATURDAY],
    open: true,
    prepMinutes: 60,
    deliveryBob: 8,
    managerName: 'Rosario Colque',
  },
  {
    id: 'b-yungas-la-paz',
    slug: 'la-paz',
    companyId: 'c-yungas',
    name: 'Casa Yungas La Paz',
    cityId: 'la-paz',
    zone: 'Obrajes',
    address: 'Av. Hernando Siles 5720',
    phone: '2 278 9925',
    point: { x: 25, y: 61 },
    hours: [WEEKDAYS],
    open: true,
    prepMinutes: 60,
    deliveryBob: 9,
    managerName: 'Hugo Barrientos',
  },
];
