import { ChatThread } from './chat.model';

export const THREADS: readonly ChatThread[] = [
  {
    id: 'th-1041',
    orderCode: 'TO-1041',
    counterpart: {
      kind: 'sucursal',
      branchId: 'b-copacabana-miraflores',
      since: '2026-08-15T13:14:00',
    },
    counterpartName: 'Copacabana Miraflores',
    messages: [
      {
        id: 'm-1041-1',
        threadId: 'th-1041',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo revisa, hablas con Copacabana Miraflores.',
        at: '2026-08-15T13:14:00',
      },
    ],
  },
  {
    id: 'th-1042',
    orderCode: 'TO-1042',
    counterpart: {
      kind: 'sucursal',
      branchId: 'b-copacabana-sopocachi',
      since: '2026-08-15T12:58:00',
    },
    counterpartName: 'Copacabana Sopocachi',
    messages: [
      {
        id: 'm-1042-1',
        threadId: 'th-1042',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo revisa, hablas con Copacabana Sopocachi.',
        at: '2026-08-15T12:58:00',
      },
      {
        id: 'm-1042-2',
        threadId: 'th-1042',
        author: 'comprador',
        authorName: 'Rosa Villca',
        body: '¿Sale con llajua aparte?',
        at: '2026-08-15T13:05:00',
      },
      {
        id: 'm-1042-3',
        threadId: 'th-1042',
        author: 'sucursal',
        authorName: 'Freddy Ticona',
        body: 'Sí, va aparte. Ya está listo, estamos buscando rider.',
        at: '2026-08-15T13:09:00',
      },
    ],
  },
  {
    id: 'th-1043',
    orderCode: 'TO-1043',
    counterpart: { kind: 'rider', riderId: 'r-marco', since: '2026-08-15T13:02:00' },
    counterpartName: 'Marco Quispe',
    messages: [
      {
        id: 'm-1043-1',
        threadId: 'th-1043',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Marco Quispe recogió tu pedido en Copacabana Miraflores. Ahora hablas con él.',
        at: '2026-08-15T13:02:00',
      },
      {
        id: 'm-1043-2',
        threadId: 'th-1043',
        author: 'rider',
        authorName: 'Marco Quispe',
        body: 'Voy saliendo, llego en unos quince minutos.',
        at: '2026-08-15T13:04:00',
      },
      {
        id: 'm-1043-3',
        threadId: 'th-1043',
        author: 'comprador',
        authorName: 'Rosa Villca',
        body: 'Perfecto. Es el portón verde, timbre de la izquierda.',
        at: '2026-08-15T13:06:00',
      },
    ],
  },
  {
    id: 'th-1044',
    orderCode: 'TO-1044',
    counterpart: { kind: 'rider', riderId: 'r-noemi', since: '2026-08-15T12:51:00' },
    counterpartName: 'Noemí Flores',
    messages: [
      {
        id: 'm-1044-1',
        threadId: 'th-1044',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Noemí Flores recogió tu pedido en Sushi Illimani San Miguel. Ahora hablas con ella.',
        at: '2026-08-15T12:51:00',
      },
      {
        id: 'm-1044-2',
        threadId: 'th-1044',
        author: 'rider',
        authorName: 'Noemí Flores',
        body: 'En camino. Hay tráfico en la avenida, pero llego.',
        at: '2026-08-15T13:08:00',
      },
    ],
  },
  {
    id: 'th-1045',
    orderCode: 'TO-1045',
    counterpart: { kind: 'rider', riderId: 'r-gabriela', since: '2026-08-15T11:40:00' },
    counterpartName: 'Gabriela Suárez',
    messages: [
      {
        id: 'm-1045-1',
        threadId: 'th-1045',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Gabriela Suárez recogió tu pedido en Sabor Oriental Equipetrol. Ahora hablas con ella.',
        at: '2026-08-15T11:40:00',
      },
      {
        id: 'm-1045-2',
        threadId: 'th-1045',
        author: 'rider',
        authorName: 'Gabriela Suárez',
        body: 'Estoy en la puerta.',
        at: '2026-08-15T12:02:00',
      },
      {
        id: 'm-1045-3',
        threadId: 'th-1045',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Gabriela Suárez escaneó tu código. Pedido entregado.',
        at: '2026-08-15T12:06:00',
      },
    ],
  },
  {
    id: 'th-1046',
    orderCode: 'TO-1046',
    counterpart: { kind: 'sucursal', branchId: 'b-oriental-norte', since: '2026-08-15T12:20:00' },
    counterpartName: 'Sabor Oriental Norte',
    messages: [
      {
        id: 'm-1046-1',
        threadId: 'th-1046',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo revisa, hablas con Sabor Oriental Norte.',
        at: '2026-08-15T12:20:00',
      },
      {
        id: 'm-1046-2',
        threadId: 'th-1046',
        author: 'sucursal',
        authorName: 'Karen Suárez',
        body: 'Disculpa, se nos acabó el keperí de hoy. Tuvimos que rechazar el pedido.',
        at: '2026-08-15T12:28:00',
      },
      {
        id: 'm-1046-3',
        threadId: 'th-1046',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La sucursal rechazó tu pedido. No se te cobró nada.',
        at: '2026-08-15T12:28:00',
      },
    ],
  },
  {
    id: 'th-2201',
    orderCode: 'TO-2201',
    counterpart: { kind: 'sucursal', branchId: 'b-tecno-la-paz', since: '2026-08-15T12:44:00' },
    counterpartName: 'Tecno La Paz',
    messages: [
      {
        id: 'm-2201-1',
        threadId: 'th-2201',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo prepara, hablas con Tecno La Paz.',
        at: '2026-08-15T12:44:00',
      },
      {
        id: 'm-2201-2',
        threadId: 'th-2201',
        author: 'sucursal',
        authorName: 'Gabriela Nina',
        body: 'Ya está embalado con la boleta de garantía adentro. Buscamos rider.',
        at: '2026-08-15T13:01:00',
      },
    ],
  },
  {
    id: 'th-2202',
    orderCode: 'TO-2202',
    counterpart: { kind: 'rider', riderId: 'r-lucia', since: '2026-08-15T12:35:00' },
    counterpartName: 'Lucía Vega',
    messages: [
      {
        id: 'm-2202-1',
        threadId: 'th-2202',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Lucía Vega recogió tu pedido en Ale Cochabamba. Ahora hablas con ella.',
        at: '2026-08-15T12:35:00',
      },
      {
        id: 'm-2202-2',
        threadId: 'th-2202',
        author: 'comprador',
        authorName: 'Elsa Rocha',
        body: 'Estoy en el trabajo, ¿puede dejarlo en portería?',
        at: '2026-08-15T12:47:00',
      },
      {
        id: 'm-2202-3',
        threadId: 'th-2202',
        author: 'rider',
        authorName: 'Lucía Vega',
        body: 'Necesito que escanees el código, así que mejor bajas un minuto.',
        at: '2026-08-15T12:49:00',
      },
    ],
  },
  {
    id: 'th-2203',
    orderCode: 'TO-2203',
    counterpart: { kind: 'sucursal', branchId: 'b-ale-la-paz', since: '2026-08-15T10:12:00' },
    counterpartName: 'Ale La Paz',
    messages: [
      {
        id: 'm-2203-1',
        threadId: 'th-2203',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo prepara, hablas con Ale La Paz.',
        at: '2026-08-15T10:12:00',
      },
      {
        id: 'm-2203-2',
        threadId: 'th-2203',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido está en la carga hacia Santa Cruz, esperando a que salga el camión.',
        at: '2026-08-15T11:05:00',
      },
      {
        id: 'm-2203-3',
        threadId: 'th-2203',
        author: 'comprador',
        authorName: 'Marcela Áñez',
        body: '¿Cuándo sale más o menos?',
        at: '2026-08-15T12:30:00',
      },
      {
        id: 'm-2203-4',
        threadId: 'th-2203',
        author: 'sucursal',
        authorName: 'Ale Quisbert',
        body: 'Faltan tres pedidos para completar. Calculamos salir mañana temprano.',
        at: '2026-08-15T12:41:00',
      },
    ],
  },
  {
    id: 'th-2204',
    orderCode: 'TO-2204',
    counterpart: { kind: 'rider', riderId: 'r-elias', since: '2026-08-15T07:30:00' },
    counterpartName: 'Elías Poma',
    messages: [
      {
        id: 'm-2204-1',
        threadId: 'th-2204',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Hiciste tu pedido. Mientras la sucursal lo prepara, hablas con Tecno Cochabamba.',
        at: '2026-08-14T16:20:00',
      },
      {
        id: 'm-2204-2',
        threadId: 'th-2204',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Tecno Cochabamba hacia La Paz con Elías Poma. Ahora hablas con él.',
        at: '2026-08-15T07:30:00',
      },
      {
        id: 'm-2204-3',
        threadId: 'th-2204',
        author: 'rider',
        authorName: 'Elías Poma',
        body: 'Vamos por Caracollo. Llegamos a La Paz por la tarde.',
        at: '2026-08-15T11:15:00',
      },
    ],
  },
  {
    id: 'th-2205',
    orderCode: 'TO-2205',
    counterpart: { kind: 'rider', riderId: 'r-marco', since: '2026-08-15T12:55:00' },
    counterpartName: 'Marco Quispe',
    messages: [
      {
        id: 'm-2205-1',
        threadId: 'th-2205',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Ale Santa Cruz hacia La Paz con Hugo Barrientos. Ahora hablas con él.',
        at: '2026-08-14T06:40:00',
      },
      {
        id: 'm-2205-2',
        threadId: 'th-2205',
        author: 'rider',
        authorName: 'Hugo Barrientos',
        body: 'Salimos completos, llegamos mañana a media mañana.',
        at: '2026-08-14T06:52:00',
      },
      {
        id: 'm-2205-3',
        threadId: 'th-2205',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido llegó a Ale La Paz. Ahora hablas con Ale Quisbert, gerente de sucursal.',
        at: '2026-08-15T10:20:00',
      },
      {
        id: 'm-2205-4',
        threadId: 'th-2205',
        author: 'comprador',
        authorName: 'Rosa Villca',
        body: 'Pedí entrega a domicilio, ¿sigue así?',
        at: '2026-08-15T10:34:00',
      },
      {
        id: 'm-2205-5',
        threadId: 'th-2205',
        author: 'sucursal',
        authorName: 'Ale Quisbert',
        body: 'Sí. Te asigno un rider en cuanto haya uno libre.',
        at: '2026-08-15T10:40:00',
      },
      {
        id: 'm-2205-6',
        threadId: 'th-2205',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Marco Quispe recogió tu pedido en Ale La Paz. Ahora hablas con él.',
        at: '2026-08-15T12:55:00',
      },
      {
        id: 'm-2205-7',
        threadId: 'th-2205',
        author: 'rider',
        authorName: 'Marco Quispe',
        body: 'Voy en camino, son dos cajas.',
        at: '2026-08-15T12:58:00',
      },
    ],
  },
  {
    id: 'th-2206',
    orderCode: 'TO-2206',
    counterpart: { kind: 'sucursal', branchId: 'b-andes-la-paz', since: '2026-08-15T09:15:00' },
    counterpartName: 'Andes La Paz',
    messages: [
      {
        id: 'm-2206-1',
        threadId: 'th-2206',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Andes Santa Cruz hacia La Paz con Elías Poma. Ahora hablas con él.',
        at: '2026-08-14T07:10:00',
      },
      {
        id: 'm-2206-2',
        threadId: 'th-2206',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido llegó a Andes La Paz. Ahora hablas con Sonia Apaza, gerente de sucursal.',
        at: '2026-08-15T09:15:00',
      },
      {
        id: 'm-2206-3',
        threadId: 'th-2206',
        author: 'sucursal',
        authorName: 'Sonia Apaza',
        body: 'Tu paquete está en mostrador. Traé tu código y tu carnet.',
        at: '2026-08-15T09:18:00',
      },
      {
        id: 'm-2206-4',
        threadId: 'th-2206',
        author: 'comprador',
        authorName: 'Julio Ramos',
        body: 'Paso mañana en la mañana.',
        at: '2026-08-15T10:02:00',
      },
    ],
  },
  {
    id: 'th-2207',
    orderCode: 'TO-2207',
    counterpart: { kind: 'sucursal', branchId: 'b-ale-cochabamba', since: '2026-08-13T08:40:00' },
    counterpartName: 'Ale Cochabamba',
    messages: [
      {
        id: 'm-2207-1',
        threadId: 'th-2207',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Ale La Paz hacia Cochabamba con Hugo Barrientos. Ahora hablas con él.',
        at: '2026-08-12T06:30:00',
      },
      {
        id: 'm-2207-2',
        threadId: 'th-2207',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido llegó a Ale Cochabamba. Ahora hablas con Mauricio Peña, gerente de sucursal.',
        at: '2026-08-13T08:40:00',
      },
      {
        id: 'm-2207-3',
        threadId: 'th-2207',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Mauricio Peña escaneó tu código en mostrador. Pedido entregado.',
        at: '2026-08-13T17:22:00',
      },
    ],
  },
  {
    id: 'th-2208',
    orderCode: 'TO-2208',
    counterpart: { kind: 'rider', riderId: 'r-lucia', since: '2026-08-13T14:05:00' },
    counterpartName: 'Lucía Vega',
    messages: [
      {
        id: 'm-2208-1',
        threadId: 'th-2208',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Ale La Paz hacia Cochabamba con Hugo Barrientos. Ahora hablas con él.',
        at: '2026-08-12T06:30:00',
      },
      {
        id: 'm-2208-2',
        threadId: 'th-2208',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido llegó a Ale Cochabamba. Ahora hablas con Mauricio Peña, gerente de sucursal.',
        at: '2026-08-13T08:40:00',
      },
      {
        id: 'm-2208-3',
        threadId: 'th-2208',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Lucía Vega recogió tu pedido en Ale Cochabamba. Ahora hablas con ella.',
        at: '2026-08-13T14:05:00',
      },
      {
        id: 'm-2208-4',
        threadId: 'th-2208',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Lucía Vega escaneó tu código. Pedido entregado.',
        at: '2026-08-13T15:12:00',
      },
    ],
  },
  {
    id: 'th-2214',
    orderCode: 'TO-2214',
    counterpart: { kind: 'sucursal', branchId: 'b-ale-la-paz', since: '2026-08-15T10:20:00' },
    counterpartName: 'Ale La Paz',
    messages: [
      {
        id: 'm-2214-1',
        threadId: 'th-2214',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Ale Santa Cruz hacia La Paz con Hugo Barrientos. Ahora hablas con él.',
        at: '2026-08-14T06:40:00',
      },
      {
        id: 'm-2214-2',
        threadId: 'th-2214',
        author: 'sistema',
        authorName: 'Touno',
        body: 'Tu pedido llegó a Ale La Paz. Ahora hablas con Ale Quisbert, gerente de sucursal.',
        at: '2026-08-15T10:20:00',
      },
      {
        id: 'm-2214-3',
        threadId: 'th-2214',
        author: 'sucursal',
        authorName: 'Ale Quisbert',
        body: 'Tu paquete está en mostrador. Traé tu código y tu carnet.',
        at: '2026-08-15T10:25:00',
      },
    ],
  },
  {
    id: 'th-2215',
    orderCode: 'TO-2215',
    counterpart: { kind: 'rider', riderId: 'r-hugo', since: '2026-08-15T06:50:00' },
    counterpartName: 'Hugo Barrientos',
    messages: [
      {
        id: 'm-2215-1',
        threadId: 'th-2215',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Santa Cruz. Ahora hablas con Hugo Barrientos, que la trae en camión.',
        at: '2026-08-15T06:50:00',
      },
    ],
  },
  {
    id: 'th-2216',
    orderCode: 'TO-2216',
    counterpart: { kind: 'rider', riderId: 'r-hugo', since: '2026-08-15T06:50:00' },
    counterpartName: 'Hugo Barrientos',
    messages: [
      {
        id: 'm-2216-1',
        threadId: 'th-2216',
        author: 'sistema',
        authorName: 'Touno',
        body: 'La carga salió de Santa Cruz. Ahora hablas con Hugo Barrientos, que la trae en camión.',
        at: '2026-08-15T06:50:00',
      },
    ],
  },
];
