import { Promotion } from './promotions.model';

export const PROMOTIONS: readonly Promotion[] = [
  {
    code: 'COPA10',
    companyId: 'c-copacabana',
    label: 'Bs 10 de descuento en combos',
    uses: 128,
    limit: 300,
    active: true,
    until: '2026-09-30',
    discount: { kind: 'amount', value: 10 },
  },
  {
    code: 'COPA20',
    companyId: 'c-copacabana',
    label: '20 % en toda la carta, hasta Bs 25',
    uses: 64,
    limit: 500,
    active: true,
    until: '2026-10-31',
    discount: { kind: 'percent', value: 20, capBob: 25 },
  },
  {
    code: 'FIELES',
    companyId: 'c-copacabana',
    label: '15 % para quien recibe siempre a la primera',
    uses: 3,
    limit: 100,
    active: true,
    until: '2026-10-31',
    discount: { kind: 'percent', value: 15, capBob: 30, minReputationPct: 98 },
  },
  {
    code: 'SALTENA',
    companyId: 'c-copacabana',
    label: 'Bs 5 en la segunda salteña',
    uses: 12,
    limit: 300,
    active: false,
    until: '2026-09-30',
    discount: { kind: 'amount', value: 5 },
  },
  {
    code: 'ORIENTAL15',
    companyId: 'c-oriental',
    label: 'Bs 15 en tu primer majadito',
    uses: 200,
    limit: 200,
    active: true,
    until: '2026-10-15',
    discount: { kind: 'amount', value: 15 },
  },
  {
    code: 'COPAPICO',
    companyId: 'c-copacabana',
    label: '10 % en la hora del almuerzo',
    uses: 27,
    limit: 400,
    active: true,
    until: '2026-09-20',
    discount: { kind: 'percent', value: 10, capBob: 20 },
    riderLeg: {
      mode: 'normal',
      perTripBob: 13,
      bonusAfterRuns: 20,
      bonusBob: 200,
      guaranteedBob: 280,
    },
  },
  {
    code: 'COPANOCHE',
    companyId: 'c-copacabana',
    label: 'Pata de rider para el turno de la noche',
    uses: 0,
    limit: 80,
    active: true,
    until: '2026-10-31',
    riderLeg: {
      mode: 'normal',
      perTripBob: 14,
      bonusAfterRuns: 15,
      bonusBob: 150,
      guaranteedBob: 260,
    },
  },
  {
    code: 'ALEENVIO',
    companyId: 'c-ale',
    label: 'Mitad del envío en compras a otra ciudad',
    uses: 61,
    limit: 150,
    active: true,
    until: '2026-09-15',
    discount: { kind: 'delivery', value: 50 },
  },
  {
    code: 'ALEGRATIS',
    companyId: 'c-ale',
    label: 'Envío gratis para quien cumple, hasta Bs 40',
    uses: 18,
    limit: 120,
    active: true,
    until: '2026-09-30',
    discount: { kind: 'delivery', value: 100, capBob: 40, minReputationPct: 90 },
  },
  {
    code: 'JULIO15',
    companyId: 'c-ale',
    label: 'Bs 15 por el aniversario de julio',
    uses: 90,
    limit: 200,
    active: true,
    until: '2026-07-31',
    discount: { kind: 'amount', value: 15 },
  },
];
