import { Addon, BranchStock, Product, Variant } from './catalog.model';

const SIZES: readonly Variant[] = [
  { id: 'personal', label: 'Personal', deltaBob: 0 },
  { id: 'familiar', label: 'Familiar', deltaBob: 28 },
];

const EXTRAS: readonly Addon[] = [
  { id: 'papas', label: 'Papas extra', priceBob: 8 },
  { id: 'llajua', label: 'Llajua de la casa', priceBob: 3 },
  { id: 'gaseosa', label: 'Gaseosa 500 ml', priceBob: 10 },
];

const GARANTIA: readonly Addon[] = [
  { id: 'garantia-extra', label: 'Un año más de garantía', priceBob: 90 },
  { id: 'instalacion', label: 'Configuración en tienda', priceBob: 40 },
];

const TALLAS: readonly Variant[] = [
  { id: 'talla-s', label: 'S', deltaBob: 0 },
  { id: 'talla-m', label: 'M', deltaBob: 0 },
  { id: 'talla-l', label: 'L', deltaBob: 15 },
];

export const PRODUCTS: readonly Product[] = [
  {
    id: 'pc-combo-familiar',
    companyId: 'c-copacabana',
    category: 'Combos',
    name: 'Combo familiar 8 presas',
    description: 'Ocho presas broaster, papas, arroz y dos salsas de la casa.',
    priceBob: 145,
    featured: true,
    soldThisMonth: 412,
    variants: SIZES,
    addons: EXTRAS,
  },
  {
    id: 'pc-cuarto-pollo',
    companyId: 'c-copacabana',
    category: 'Pollo',
    name: 'Cuarto de pollo con papas',
    description: 'Presa broaster, papas doradas y llajua.',
    priceBob: 38,
    featured: false,
    soldThisMonth: 906,
    variants: [],
    addons: EXTRAS,
  },
  {
    id: 'pc-saltena-carne',
    companyId: 'c-copacabana',
    category: 'Salteñas',
    name: 'Salteña de carne',
    description: 'Jugosa, con aceituna y huevo, horneada a las nueve.',
    priceBob: 9,
    featured: true,
    soldThisMonth: 1580,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-sopa-mani',
    companyId: 'c-copacabana',
    category: 'Combos',
    name: 'Sopa de maní',
    description: 'Con papa frita encima, como corresponde.',
    priceBob: 26,
    featured: false,
    soldThisMonth: 344,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-mocochinchi',
    companyId: 'c-copacabana',
    category: 'Bebidas',
    name: 'Mocochinchi',
    description: 'Refresco de durazno pelado, bien frío.',
    priceBob: 8,
    featured: false,
    soldThisMonth: 720,
    variants: [],
    addons: [],
  },
  {
    id: 'so-majadito',
    companyId: 'c-oriental',
    category: 'Platos',
    name: 'Majadito batido',
    description: 'Arroz con charque, plátano frito y huevo.',
    priceBob: 42,
    featured: true,
    soldThisMonth: 388,
    variants: [],
    addons: [],
  },
  {
    id: 'so-keperi',
    companyId: 'c-oriental',
    category: 'Platos',
    name: 'Keperí al horno',
    description: 'Corte camba cocido lento, con yuca y sonso.',
    priceBob: 68,
    featured: true,
    soldThisMonth: 214,
    variants: [],
    addons: [],
  },
  {
    id: 'so-cunape',
    companyId: 'c-oriental',
    category: 'Horneados',
    name: 'Cuñapé por seis',
    description: 'Recién salido, con queso chaqueño.',
    priceBob: 18,
    featured: false,
    soldThisMonth: 640,
    variants: [],
    addons: [],
  },
  {
    id: 'so-zonzo',
    companyId: 'c-oriental',
    category: 'Horneados',
    name: 'Sonso de yuca',
    description: 'A la parrilla, con queso hilado.',
    priceBob: 15,
    featured: false,
    soldThisMonth: 402,
    variants: [],
    addons: [],
  },
  {
    id: 'so-somo',
    companyId: 'c-oriental',
    category: 'Bebidas',
    name: 'Somó de maíz',
    description: 'Espeso y con canela.',
    priceBob: 10,
    featured: false,
    soldThisMonth: 288,
    variants: [],
    addons: [],
  },
  {
    id: 'si-roll-titicaca',
    companyId: 'c-illimani',
    category: 'Rolls',
    name: 'Roll Titicaca',
    description: 'Trucha, palta y sésamo tostado, ocho piezas.',
    priceBob: 62,
    featured: true,
    soldThisMonth: 266,
    variants: [],
    addons: [],
  },
  {
    id: 'si-roll-illimani',
    companyId: 'c-illimani',
    category: 'Rolls',
    name: 'Roll Illimani',
    description: 'Salmón, queso crema y cebollín, ocho piezas.',
    priceBob: 74,
    featured: false,
    soldThisMonth: 198,
    variants: [],
    addons: [],
  },
  {
    id: 'si-gyoza',
    companyId: 'c-illimani',
    category: 'Entradas',
    name: 'Gyoza de cerdo',
    description: 'Cinco unidades, selladas a la plancha.',
    priceBob: 34,
    featured: false,
    soldThisMonth: 176,
    variants: [],
    addons: [],
  },
  {
    id: 'si-edamame',
    companyId: 'c-illimani',
    category: 'Entradas',
    name: 'Edamame con sal marina',
    description: 'Vaina tibia, para empezar.',
    priceBob: 22,
    featured: false,
    soldThisMonth: 132,
    variants: [],
    addons: [],
  },
  {
    id: 'si-te-verde',
    companyId: 'c-illimani',
    category: 'Bebidas',
    name: 'Té verde frío',
    description: 'Sin azúcar, en jarra de medio litro.',
    priceBob: 14,
    featured: false,
    soldThisMonth: 210,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-desayuno-sucre',
    companyId: 'c-cafe-sucre',
    category: 'Desayunos',
    name: 'Desayuno sucrense',
    description: 'Café con leche, jugo, huevos y pan de trigo.',
    priceBob: 38,
    featured: true,
    soldThisMonth: 512,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-torta-chocolate',
    companyId: 'c-cafe-sucre',
    category: 'Tortas',
    name: 'Torta de chocolate',
    description: 'Porción alta, con ganache oscuro.',
    priceBob: 24,
    featured: true,
    soldThisMonth: 448,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-cheesecake',
    companyId: 'c-cafe-sucre',
    category: 'Tortas',
    name: 'Cheesecake de maracuyá',
    description: 'Base de galleta y cobertura ácida.',
    priceBob: 26,
    featured: false,
    soldThisMonth: 302,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-cafe-yungas',
    companyId: 'c-cafe-sucre',
    category: 'Café',
    name: 'Café de yungas, 250 g',
    description: 'Tostado en casa, molido o en grano.',
    priceBob: 55,
    featured: false,
    soldThisMonth: 188,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-api-pastel',
    companyId: 'c-cafe-sucre',
    category: 'Desayunos',
    name: 'Api con pastel',
    description: 'Api morado espeso y pastel de queso.',
    priceBob: 16,
    featured: false,
    soldThisMonth: 690,
    variants: [],
    addons: [],
  },
  {
    id: 'al-campera',
    companyId: 'c-ale',
    category: 'Ropa',
    name: 'Campera impermeable',
    description: 'Corta viento con capucha guardable.',
    priceBob: 320,
    featured: true,
    soldThisMonth: 84,
    variants: TALLAS,
    addons: [],
  },
  {
    id: 'al-jean',
    companyId: 'c-ale',
    category: 'Ropa',
    name: 'Jean recto',
    description: 'Algodón con elastano, corte clásico.',
    priceBob: 210,
    featured: false,
    soldThisMonth: 132,
    variants: TALLAS,
    addons: [],
  },
  {
    id: 'al-zapatilla',
    companyId: 'c-ale',
    category: 'Calzado',
    name: 'Zapatilla urbana',
    description: 'Suela de goma, del 36 al 44.',
    priceBob: 380,
    featured: true,
    soldThisMonth: 96,
    variants: [],
    addons: [],
  },
  {
    id: 'al-mochila',
    companyId: 'c-ale',
    category: 'Accesorios',
    name: 'Mochila 25 litros',
    description: 'Con bolsillo acolchado para laptop.',
    priceBob: 245,
    featured: false,
    soldThisMonth: 71,
    variants: [],
    addons: [],
  },
  {
    id: 'al-gorra',
    companyId: 'c-ale',
    category: 'Accesorios',
    name: 'Gorra de lona',
    description: 'Visera curva, talla ajustable.',
    priceBob: 75,
    featured: false,
    soldThisMonth: 154,
    variants: [],
    addons: [],
  },
  {
    id: 'an-taladro',
    companyId: 'c-andes',
    category: 'Herramienta',
    name: 'Taladro percutor 750 W',
    description: 'Con maletín, mandril de 13 mm.',
    priceBob: 690,
    featured: true,
    soldThisMonth: 48,
    variants: [],
    addons: [],
  },
  {
    id: 'an-juego-llaves',
    companyId: 'c-andes',
    category: 'Herramienta',
    name: 'Juego de llaves, 24 piezas',
    description: 'Acero cromo vanadio, del 6 al 32.',
    priceBob: 420,
    featured: false,
    soldThisMonth: 62,
    variants: [],
    addons: [],
  },
  {
    id: 'an-casco',
    companyId: 'c-andes',
    category: 'Repuestos',
    name: 'Casco integral certificado',
    description: 'Visor antirrayas, tallas M a XL.',
    priceBob: 540,
    featured: true,
    soldThisMonth: 77,
    variants: [],
    addons: [],
  },
  {
    id: 'an-cadena',
    companyId: 'c-andes',
    category: 'Repuestos',
    name: 'Kit de arrastre 428',
    description: 'Cadena, piñón y catalina reforzados.',
    priceBob: 310,
    featured: false,
    soldThisMonth: 93,
    variants: [],
    addons: [],
  },
  {
    id: 'an-candado',
    companyId: 'c-andes',
    category: 'Ferretería',
    name: 'Candado de disco',
    description: 'Con alarma y cable recordatorio.',
    priceBob: 180,
    featured: false,
    soldThisMonth: 118,
    variants: [],
    addons: [],
  },
  {
    id: 'tb-celular-medio',
    companyId: 'c-tecno',
    category: 'Celulares',
    name: 'Celular 128 GB',
    description: 'Pantalla de 6,6 pulgadas y batería de 5000 mAh.',
    priceBob: 1890,
    featured: true,
    soldThisMonth: 143,
    variants: [],
    addons: GARANTIA,
  },
  {
    id: 'tb-celular-alto',
    companyId: 'c-tecno',
    category: 'Celulares',
    name: 'Celular 256 GB con carga rápida',
    description: 'Carga al 60 por ciento en media hora.',
    priceBob: 3250,
    featured: false,
    soldThisMonth: 68,
    variants: [],
    addons: GARANTIA,
  },
  {
    id: 'tb-audifonos',
    companyId: 'c-tecno',
    category: 'Audio',
    name: 'Audífonos con cancelación',
    description: 'Treinta horas de batería y estuche de carga.',
    priceBob: 780,
    featured: true,
    soldThisMonth: 205,
    variants: [],
    addons: [],
  },
  {
    id: 'tb-parlante',
    companyId: 'c-tecno',
    category: 'Audio',
    name: 'Parlante resistente al agua',
    description: 'Doce horas de reproducción, correa incluida.',
    priceBob: 520,
    featured: false,
    soldThisMonth: 161,
    variants: [],
    addons: [],
  },
  {
    id: 'tb-cargador',
    companyId: 'c-tecno',
    category: 'Accesorios',
    name: 'Cargador de 65 W',
    description: 'Dos puertos, con cable trenzado.',
    priceBob: 240,
    featured: false,
    soldThisMonth: 288,
    variants: [],
    addons: [],
  },
  {
    id: 'cy-olla-presion',
    companyId: 'c-yungas',
    category: 'Menaje',
    name: 'Olla a presión de 6 litros',
    description: 'Aluminio grueso, con válvula de seguridad.',
    priceBob: 430,
    featured: true,
    soldThisMonth: 59,
    variants: [],
    addons: [],
  },
  {
    id: 'cy-juego-sartenes',
    companyId: 'c-yungas',
    category: 'Menaje',
    name: 'Juego de tres sartenes',
    description: 'Antiadherente reforzado, aptas para gas.',
    priceBob: 365,
    featured: false,
    soldThisMonth: 74,
    variants: [],
    addons: [],
  },
  {
    id: 'cy-edredon',
    companyId: 'c-yungas',
    category: 'Textil',
    name: 'Edredón dos plazas',
    description: 'Relleno siliconado, funda de microfibra.',
    priceBob: 395,
    featured: true,
    soldThisMonth: 88,
    variants: [],
    addons: [],
  },
  {
    id: 'cy-toallas',
    companyId: 'c-yungas',
    category: 'Textil',
    name: 'Juego de toallas',
    description: 'Algodón peinado, cuatro piezas.',
    priceBob: 185,
    featured: false,
    soldThisMonth: 112,
    variants: [],
    addons: [],
  },
  {
    id: 'cy-hervidor',
    companyId: 'c-yungas',
    category: 'Hogar',
    name: 'Hervidor eléctrico 1,7 litros',
    description: 'Apagado automático y base giratoria.',
    priceBob: 210,
    featured: false,
    soldThisMonth: 136,
    variants: [],
    addons: [],
  },
];

export const BRANCH_STOCK: readonly BranchStock[] = [
  { branchId: 'b-copacabana-sopocachi', productId: 'pc-sopa-mani', available: false },
  { branchId: 'b-copacabana-cala-cala', productId: 'pc-saltena-carne', available: false },
  { branchId: 'b-oriental-norte', productId: 'so-keperi', available: false },
  { branchId: 'b-cafe-sucre-recoleta', productId: 'cs-cafe-yungas', available: false },
  { branchId: 'b-ale-cochabamba', productId: 'al-zapatilla', available: false },
  { branchId: 'b-andes-sucre', productId: 'an-taladro', available: false },
  { branchId: 'b-tecno-la-paz', productId: 'tb-celular-alto', available: false },
  { branchId: 'b-yungas-la-paz', productId: 'cy-olla-presion', available: false },
];
