import { Driver, HiringOffer, Payout, Ride } from './drivers.model';

export const DRIVERS: readonly Driver[] = [
  {
    id: 'd-marco',
    slug: 'marco-quispe',
    name: 'Marco Quispe',
    plate: '3421 KZP',
    vehicle: 'moto',
    city: 'La Paz',
    zones: ['Miraflores', 'Centro', 'Sopocachi'],
    rating: 4.9,
    ridesDone: 1842,
    onTimePct: 98,
    available: true,
    ratePerRideBob: 15,
    account: '•••• 4408 · Banco Unión',
  },
  {
    id: 'd-ivan',
    slug: 'ivan-rocha',
    name: 'Iván Rocha',
    plate: '2870 LFA',
    vehicle: 'auto',
    city: 'La Paz',
    zones: ['Zona Sur', 'San Miguel', 'Calacoto'],
    rating: 4.7,
    ridesDone: 976,
    onTimePct: 95,
    available: true,
    ratePerRideBob: 18,
    account: '•••• 2211 · Banco Mercantil',
  },
  {
    id: 'd-noemi',
    slug: 'noemi-arce',
    name: 'Noemí Arce',
    plate: '5512 HRT',
    vehicle: 'moto',
    city: 'Santa Cruz',
    zones: ['Equipetrol', 'Centro', 'Segundo Anillo'],
    rating: 4.8,
    ridesDone: 1310,
    onTimePct: 97,
    available: true,
    ratePerRideBob: 16,
    account: '•••• 7745 · Banco Ganadero',
  },
  {
    id: 'd-rene',
    slug: 'rene-mamani',
    name: 'René Mamani',
    plate: '9087 KKA',
    vehicle: 'camioneta',
    city: 'Cochabamba',
    zones: ['Cala Cala', 'Quillacollo', 'Centro'],
    rating: 4.5,
    ridesDone: 604,
    onTimePct: 92,
    available: false,
    ratePerRideBob: 22,
    account: '•••• 3390 · Banco BISA',
  },
  {
    id: 'd-gabriela',
    slug: 'gabriela-flores',
    name: 'Gabriela Flores',
    plate: '7712 GGP',
    vehicle: 'moto',
    city: 'La Paz',
    zones: ['El Alto', 'Villa Fátima'],
    rating: 4.6,
    ridesDone: 812,
    onTimePct: 94,
    available: true,
    ratePerRideBob: 14,
    account: '•••• 5521 · Banco Unión',
  },
  {
    id: 'd-alvaro',
    slug: 'alvaro-condori',
    name: 'Álvaro Condori',
    plate: '4410 PLC',
    vehicle: 'auto',
    city: 'Santa Cruz',
    zones: ['Urubó', 'Plan 3000'],
    rating: 4.4,
    ridesDone: 431,
    onTimePct: 90,
    available: true,
    ratePerRideBob: 20,
    account: '•••• 1180 · Banco Fassil',
  },
  {
    id: 'd-lucia',
    slug: 'lucia-tarqui',
    name: 'Lucía Tarqui',
    plate: '6620 JJD',
    vehicle: 'moto',
    city: 'Oruro',
    zones: ['Centro', 'Norte'],
    rating: 4.8,
    ridesDone: 389,
    onTimePct: 96,
    available: true,
    ratePerRideBob: 13,
    account: '•••• 9033 · Banco Unión',
  },
  {
    id: 'd-hugo',
    slug: 'hugo-salazar',
    name: 'Hugo Salazar',
    plate: '1204 MMB',
    vehicle: 'auto',
    city: 'Sucre',
    zones: ['Centro', 'Alto Delicias'],
    rating: 4.2,
    ridesDone: 227,
    onTimePct: 88,
    available: false,
    ratePerRideBob: 17,
    account: '•••• 6642 · Banco BISA',
  },
];

export const RIDES: readonly Ride[] = [
  {
    id: 'r-9001',
    kind: 'recojo-encomienda',
    driverId: 'd-marco',
    merchantSlug: 'importadora-ale',
    guia: 'TY-4471',
    pickup: { label: 'Importadora Ale', address: 'Av. Saavedra 1450', city: 'La Paz' },
    dropoff: { label: 'Bolívar · Terminal La Paz', address: 'Av. Perú 1780', city: 'La Paz' },
    earnBob: 15,
    state: 'entregada',
    beforeAt: '2026-08-15T13:30:00',
    photoTaken: true,
    distanceKm: 1.2,
  },
  {
    id: 'r-9002',
    kind: 'recojo-encomienda',
    driverId: 'd-ivan',
    merchantSlug: 'importadora-ale',
    guia: 'TY-4470',
    pickup: { label: 'Importadora Ale', address: 'Av. Saavedra 1450', city: 'La Paz' },
    dropoff: { label: 'Bolívar · Terminal La Paz', address: 'Av. Perú 1780', city: 'La Paz' },
    earnBob: 15,
    state: 'recogida',
    beforeAt: '2026-08-15T18:00:00',
    photoTaken: true,
    distanceKm: 1.2,
  },
  {
    id: 'r-9003',
    kind: 'recojo-encomienda',
    merchantSlug: 'importadora-ale',
    guia: 'TY-4473',
    pickup: { label: 'Importadora Ale', address: 'Av. Saavedra 1450', city: 'La Paz' },
    dropoff: { label: 'Illimani · Terminal Oruro', address: 'Calle Bakovic 1', city: 'La Paz' },
    earnBob: 15,
    state: 'ofrecida',
    beforeAt: '2026-08-15T15:30:00',
    photoTaken: false,
    distanceKm: 1.4,
  },
  {
    id: 'r-9004',
    kind: 'comida',
    driverId: 'd-marco',
    merchantSlug: 'pollos-copacabana',
    orderCode: 'TO-1042',
    pickup: { label: 'Pollos Copacabana', address: 'Av. Busch 421', city: 'La Paz' },
    dropoff: { label: 'Rosa Villca', address: 'Calle 5 de Obrajes 120', city: 'La Paz' },
    earnBob: 12,
    state: 'aceptada',
    beforeAt: '2026-08-15T13:15:00',
    photoTaken: false,
    distanceKm: 3.8,
  },
  {
    id: 'r-9005',
    kind: 'comida',
    merchantSlug: 'pollos-copacabana',
    orderCode: 'TO-1045',
    pickup: { label: 'Pollos Copacabana', address: 'Av. Busch 421', city: 'La Paz' },
    dropoff: { label: 'Carla Mendoza', address: 'Av. Arce 2130', city: 'La Paz' },
    earnBob: 14,
    state: 'ofrecida',
    beforeAt: '2026-08-15T13:40:00',
    photoTaken: false,
    distanceKm: 4.5,
  },
  {
    id: 'r-9006',
    kind: 'comida',
    driverId: 'd-noemi',
    merchantSlug: 'sabor-oriental',
    orderCode: 'TO-1039',
    pickup: { label: 'Sabor Oriental', address: 'Av. San Martín 300', city: 'Santa Cruz' },
    dropoff: { label: 'Julio Camacho', address: 'Av. Alemana 990', city: 'Santa Cruz' },
    earnBob: 13,
    state: 'entregada',
    beforeAt: '2026-08-15T12:40:00',
    photoTaken: false,
    distanceKm: 2.9,
  },
];

export const PAYOUTS: readonly Payout[] = [
  { day: '2026-08-15', label: 'Viernes 15', rides: 7, earnBob: 105 },
  { day: '2026-08-14', label: 'Jueves 14', rides: 9, earnBob: 138 },
  { day: '2026-08-13', label: 'Miércoles 13', rides: 6, earnBob: 92 },
  { day: '2026-08-12', label: 'Martes 12', rides: 8, earnBob: 121 },
  { day: '2026-08-11', label: 'Lunes 11', rides: 5, earnBob: 78 },
  { day: '2026-08-10', label: 'Domingo 10', rides: 8, earnBob: 106 },
];

export const HIRING_OFFERS: readonly HiringOffer[] = [
  {
    id: 'ho-501',
    businessSlug: 'importadora-ale',
    businessName: 'Importadora Ale',
    businessKind: 'importadora',
    driverId: 'd-marco',
    rides: 40,
    ridesUsed: 27,
    perRideBob: 15,
    totalBob: 600,
    validUntil: '2026-08-31',
    state: 'aceptada',
    message: 'Recojos de lunes a sábado, entre las 10:00 y las 18:00.',
    sentAt: '2026-08-01T09:00:00',
  },
  {
    id: 'ho-502',
    businessSlug: 'importadora-ale',
    businessName: 'Importadora Ale',
    businessKind: 'importadora',
    driverId: 'd-gabriela',
    rides: 20,
    ridesUsed: 0,
    perRideBob: 14,
    totalBob: 280,
    validUntil: '2026-08-25',
    state: 'pendiente',
    message: 'Necesitamos cubrir El Alto los días de transmisión.',
    sentAt: '2026-08-15T10:10:00',
  },
  {
    id: 'ho-503',
    businessSlug: 'pollos-copacabana',
    businessName: 'Pollos Copacabana',
    businessKind: 'restaurante',
    driverId: 'd-marco',
    rides: 60,
    ridesUsed: 0,
    perRideBob: 12,
    totalBob: 720,
    validUntil: '2026-08-30',
    state: 'pendiente',
    message: 'Turnos de almuerzo, 11:30 a 15:00.',
    sentAt: '2026-08-15T11:05:00',
  },
  {
    id: 'ho-504',
    businessSlug: 'pollos-copacabana',
    businessName: 'Pollos Copacabana',
    businessKind: 'restaurante',
    driverId: 'd-ivan',
    rides: 30,
    ridesUsed: 12,
    perRideBob: 18,
    totalBob: 540,
    validUntil: '2026-08-28',
    state: 'aceptada',
    sentAt: '2026-08-05T08:40:00',
  },
  {
    id: 'ho-505',
    businessSlug: 'sabor-oriental',
    businessName: 'Sabor Oriental',
    businessKind: 'restaurante',
    driverId: 'd-noemi',
    rides: 25,
    ridesUsed: 25,
    perRideBob: 16,
    totalBob: 400,
    validUntil: '2026-08-14',
    state: 'vencida',
    sentAt: '2026-07-28T15:20:00',
  },
  {
    id: 'ho-506',
    businessSlug: 'tecno-import',
    businessName: 'Tecno Import',
    businessKind: 'importadora',
    driverId: 'd-marco',
    rides: 15,
    ridesUsed: 0,
    perRideBob: 15,
    totalBob: 225,
    validUntil: '2026-08-20',
    state: 'rechazada',
    message: 'Recojos de celulares, con seguro de por medio.',
    sentAt: '2026-08-12T16:00:00',
  },
];
