import { Merchant } from './marketplace.model';

export const MERCHANTS: readonly Merchant[] = [
  {
    slug: 'pollos-copacabana',
    name: 'Pollos Copacabana',
    kind: 'restaurante',
    city: 'La Paz',
    zone: 'Miraflores',
    summary: 'Pollo broaster, salteñas y sopas de olla desde 1978.',
    rating: 4.7,
    reviewCount: 1284,
    open: true,
    prepMinutes: 25,
    deliveryBob: 8,
    categories: ['Combos', 'Pollo', 'Salteñas', 'Bebidas'],
    tags: ['Pollo', 'Boliviana'],
  },
  {
    slug: 'sabor-oriental',
    name: 'Sabor Oriental',
    kind: 'restaurante',
    city: 'Santa Cruz',
    zone: 'Equipetrol',
    summary: 'Majadito, keperí y cuñapé recién horneado.',
    rating: 4.6,
    reviewCount: 731,
    open: true,
    prepMinutes: 30,
    deliveryBob: 10,
    categories: ['Almuerzos', 'Parrilla', 'Horneados', 'Bebidas'],
    tags: ['Boliviana', 'Parrilla'],
  },
  {
    slug: 'la-cocina-de-dona-rita',
    name: 'La Cocina de Doña Rita',
    kind: 'restaurante',
    city: 'Cochabamba',
    zone: 'Cala Cala',
    summary: 'Silpancho, pique y chicharrón, como en casa.',
    rating: 4.8,
    reviewCount: 942,
    open: true,
    prepMinutes: 35,
    deliveryBob: 9,
    categories: ['Almuerzos', 'Platos fuertes', 'Postres'],
    tags: ['Boliviana', 'Casera'],
  },
  {
    slug: 'sushi-illimani',
    name: 'Sushi Illimani',
    kind: 'restaurante',
    city: 'La Paz',
    zone: 'San Miguel',
    summary: 'Rolls, gyozas y ramen con producto del día.',
    rating: 4.5,
    reviewCount: 508,
    open: false,
    prepMinutes: 40,
    deliveryBob: 12,
    categories: ['Rolls', 'Calientes', 'Entradas', 'Bebidas'],
    tags: ['Japonesa', 'Sushi'],
  },
  {
    slug: 'pizzeria-el-horno',
    name: 'Pizzería El Horno',
    kind: 'restaurante',
    city: 'La Paz',
    zone: 'Sopocachi',
    summary: 'Masa madre de 48 horas y horno a leña.',
    rating: 4.4,
    reviewCount: 366,
    open: true,
    prepMinutes: 30,
    deliveryBob: 10,
    categories: ['Pizzas', 'Entradas', 'Bebidas'],
    tags: ['Pizza', 'Italiana'],
  },
  {
    slug: 'burger-terminal',
    name: 'Burger Terminal',
    kind: 'restaurante',
    city: 'Oruro',
    zone: 'Centro',
    summary: 'Hamburguesas de carne madurada y papas rústicas.',
    rating: 4.3,
    reviewCount: 214,
    open: true,
    prepMinutes: 20,
    deliveryBob: 7,
    categories: ['Hamburguesas', 'Acompañamientos', 'Bebidas'],
    tags: ['Hamburguesas'],
  },
  {
    slug: 'cafe-sucre',
    name: 'Café Sucre',
    kind: 'restaurante',
    city: 'Sucre',
    zone: 'Plaza 25 de Mayo',
    summary: 'Café de yungas, tortas y desayunos todo el día.',
    rating: 4.9,
    reviewCount: 623,
    open: true,
    prepMinutes: 18,
    deliveryBob: 6,
    categories: ['Desayunos', 'Panadería', 'Café'],
    tags: ['Café', 'Desayuno'],
  },
  {
    slug: 'vegetal-y-fresco',
    name: 'Vegetal y Fresco',
    kind: 'restaurante',
    city: 'Santa Cruz',
    zone: 'Urubó',
    summary: 'Bowls, ensaladas y jugos prensados en frío.',
    rating: 4.2,
    reviewCount: 187,
    open: true,
    prepMinutes: 22,
    deliveryBob: 9,
    categories: ['Bowls', 'Ensaladas', 'Jugos'],
    tags: ['Saludable', 'Vegetariana'],
  },
  {
    slug: 'importadora-ale',
    name: 'Importadora Ale',
    kind: 'importadora',
    city: 'La Paz',
    zone: 'El Alto',
    summary: 'Ropa y calzado importado, despacho el mismo día.',
    rating: 4.6,
    reviewCount: 452,
    open: true,
    prepMinutes: 60,
    deliveryBob: 15,
    categories: ['Ropa', 'Calzado', 'Accesorios'],
    tags: ['Ropa', 'Importación'],
  },
  {
    slug: 'tecno-import',
    name: 'Tecno Import',
    kind: 'importadora',
    city: 'La Paz',
    zone: 'Max Paredes',
    summary: 'Celulares, audio y accesorios con garantía de tienda.',
    rating: 4.4,
    reviewCount: 389,
    open: true,
    prepMinutes: 90,
    deliveryBob: 15,
    categories: ['Celulares', 'Audio', 'Accesorios'],
    tags: ['Tecnología'],
  },
  {
    slug: 'hogar-y-mas',
    name: 'Hogar y Más',
    kind: 'importadora',
    city: 'Santa Cruz',
    zone: 'Plan 3000',
    summary: 'Menaje, pequeños electrodomésticos y organización.',
    rating: 4.1,
    reviewCount: 176,
    open: true,
    prepMinutes: 120,
    deliveryBob: 18,
    categories: ['Cocina', 'Organización', 'Electro'],
    tags: ['Hogar'],
  },
  {
    slug: 'moto-repuestos-bolivia',
    name: 'Moto Repuestos Bolivia',
    kind: 'importadora',
    city: 'Cochabamba',
    zone: 'Quillacollo',
    summary: 'Repuestos y llantas para moto, envío a todo el país.',
    rating: 4.5,
    reviewCount: 298,
    open: true,
    prepMinutes: 120,
    deliveryBob: 20,
    categories: ['Repuestos', 'Llantas', 'Cascos'],
    tags: ['Repuestos'],
  },
  {
    slug: 'belleza-import',
    name: 'Belleza Import',
    kind: 'importadora',
    city: 'Santa Cruz',
    zone: 'Centro',
    summary: 'Cosmética y cuidado personal de marca original.',
    rating: 4.7,
    reviewCount: 511,
    open: false,
    prepMinutes: 90,
    deliveryBob: 15,
    categories: ['Cuidado facial', 'Cabello', 'Maquillaje'],
    tags: ['Belleza'],
  },
  {
    slug: 'deportes-andinos',
    name: 'Deportes Andinos',
    kind: 'importadora',
    city: 'Oruro',
    zone: 'Centro',
    summary: 'Zapatillas, mochilas y equipamiento de montaña.',
    rating: 4.3,
    reviewCount: 143,
    open: true,
    prepMinutes: 90,
    deliveryBob: 16,
    categories: ['Calzado', 'Mochilas', 'Montaña'],
    tags: ['Deporte'],
  },
];

export const RESTAURANTS: readonly Merchant[] = MERCHANTS.filter(
  (merchant) => merchant.kind === 'restaurante',
);

export const IMPORTERS: readonly Merchant[] = MERCHANTS.filter(
  (merchant) => merchant.kind === 'importadora',
);
