import { Coupon, Order, Settlement } from './orders.model';

export const ORDERS: readonly Order[] = [
  {
    code: 'TO-1041',
    slug: 'to-1041',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-copacabana',
    originBranchId: 'b-copacabana-miraflores',
    buyer: { name: 'Rosa Villca', phone: '7712 4408' },
    buyerCityId: 'la-paz',
    address: 'Calle 5 de Obrajes 120, La Paz',
    delivery: 'domicilio',
    lines: [
      {
        productId: 'pc-combo-familiar',
        name: 'Combo familiar 8 presas',
        qty: 1,
        unitBob: 145,
        options: ['Papas extra'],
      },
      { productId: 'pc-mocochinchi', name: 'Mocochinchi', qty: 2, unitBob: 8, options: [] },
    ],
    subtotalBob: 161,
    deliveryBob: 8,
    totalBob: 169,
    state: 'nuevo',
    placedAt: '2026-08-15T13:14:00',
    promisedAt: '2026-08-15T13:52:00',
    assignments: [],
    custody: {
      kind: 'sucursal',
      branchId: 'b-copacabana-miraflores',
      since: '2026-08-15T13:14:00',
    },
    threadId: 'th-1041',
  },
  {
    code: 'TO-1042',
    slug: 'to-1042',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-copacabana',
    originBranchId: 'b-copacabana-sopocachi',
    buyer: { name: 'Rosa Villca', phone: '7712 4408' },
    buyerCityId: 'la-paz',
    address: 'Av. Ecuador 2280, La Paz',
    delivery: 'domicilio',
    lines: [
      {
        productId: 'pc-cuarto-pollo',
        name: 'Cuarto de pollo con papas',
        qty: 2,
        unitBob: 38,
        options: ['Llajua aparte'],
      },
      { productId: 'pc-saltena-carne', name: 'Salteña de carne', qty: 3, unitBob: 9, options: [] },
    ],
    subtotalBob: 103,
    deliveryBob: 8,
    totalBob: 111,
    state: 'esperando-rider',
    placedAt: '2026-08-15T12:58:00',
    promisedAt: '2026-08-15T13:40:00',
    assignments: [],
    custody: { kind: 'sucursal', branchId: 'b-copacabana-sopocachi', since: '2026-08-15T12:58:00' },
    threadId: 'th-1042',
  },
  {
    code: 'TO-1043',
    slug: 'to-1043',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-copacabana',
    originBranchId: 'b-copacabana-miraflores',
    buyer: { name: 'Rosa Villca', phone: '7712 4408' },
    buyerCityId: 'la-paz',
    address: 'Calle 5 de Obrajes 120, La Paz',
    delivery: 'domicilio',
    lines: [
      { productId: 'pc-sopa-mani', name: 'Sopa de maní', qty: 2, unitBob: 26, options: [] },
      { productId: 'pc-mocochinchi', name: 'Mocochinchi', qty: 1, unitBob: 8, options: [] },
    ],
    subtotalBob: 60,
    deliveryBob: 8,
    totalBob: 68,
    state: 'en-camino',
    placedAt: '2026-08-15T12:40:00',
    promisedAt: '2026-08-15T13:25:00',
    assignments: [
      {
        leg: 'origen',
        riderId: 'r-marco',
        branchId: 'b-copacabana-miraflores',
        assignedAt: '2026-08-15T12:58:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-marco', since: '2026-08-15T13:02:00' },
    threadId: 'th-1043',
  },
  {
    code: 'TO-1044',
    slug: 'to-1044',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-illimani',
    originBranchId: 'b-illimani-san-miguel',
    buyer: { name: 'Ernesto Villarroel', phone: '7044 1189' },
    buyerCityId: 'la-paz',
    address: 'Calle 15 de Achumani 40, La Paz',
    delivery: 'domicilio',
    lines: [
      { productId: 'si-roll-titicaca', name: 'Roll Titicaca', qty: 1, unitBob: 62, options: [] },
      { productId: 'si-gyoza', name: 'Gyoza de cerdo', qty: 1, unitBob: 34, options: [] },
    ],
    subtotalBob: 96,
    deliveryBob: 12,
    totalBob: 108,
    state: 'en-camino',
    placedAt: '2026-08-15T12:26:00',
    promisedAt: '2026-08-15T13:15:00',
    assignments: [
      {
        leg: 'origen',
        riderId: 'r-noemi',
        branchId: 'b-illimani-san-miguel',
        assignedAt: '2026-08-15T12:46:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-noemi', since: '2026-08-15T12:51:00' },
    threadId: 'th-1044',
  },
  {
    code: 'TO-1045',
    slug: 'to-1045',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-oriental',
    originBranchId: 'b-oriental-equipetrol',
    buyer: { name: 'Karina Melgar', phone: '7008 3312' },
    buyerCityId: 'santa-cruz',
    address: 'Calle Los Tajibos 88, Santa Cruz',
    delivery: 'domicilio',
    lines: [
      { productId: 'so-majadito', name: 'Majadito batido', qty: 2, unitBob: 42, options: [] },
      { productId: 'so-cunape', name: 'Cuñapé por seis', qty: 1, unitBob: 18, options: [] },
    ],
    subtotalBob: 102,
    deliveryBob: 10,
    totalBob: 112,
    state: 'entregado',
    placedAt: '2026-08-15T11:20:00',
    promisedAt: '2026-08-15T12:05:00',
    assignments: [
      {
        leg: 'origen',
        riderId: 'r-gabriela',
        branchId: 'b-oriental-equipetrol',
        assignedAt: '2026-08-15T11:36:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-gabriela', since: '2026-08-15T11:40:00' },
    threadId: 'th-1045',
    scannedAt: '2026-08-15T12:06:00',
    scannedBy: 'r-gabriela',
    review: {
      stars: 5,
      text: 'Llegó calientito y antes de la hora.',
      at: '2026-08-15T12:40:00',
      reply: 'Gracias Karina, te esperamos pronto.',
    },
  },
  {
    code: 'TO-1046',
    slug: 'to-1046',
    scenario: 'restaurante',
    type: 'restaurante',
    companyId: 'c-oriental',
    originBranchId: 'b-oriental-norte',
    buyer: { name: 'Diego Áñez', phone: '7112 5540' },
    buyerCityId: 'santa-cruz',
    address: 'Av. Banzer km 8, Santa Cruz',
    delivery: 'domicilio',
    lines: [{ productId: 'so-keperi', name: 'Keperí al horno', qty: 1, unitBob: 68, options: [] }],
    subtotalBob: 68,
    deliveryBob: 12,
    totalBob: 80,
    state: 'rechazado',
    placedAt: '2026-08-15T12:20:00',
    promisedAt: '2026-08-15T13:10:00',
    assignments: [],
    custody: { kind: 'sucursal', branchId: 'b-oriental-norte', since: '2026-08-15T12:20:00' },
    threadId: 'th-1046',
  },
  {
    code: 'TO-2201',
    slug: 'to-2201',
    scenario: 'importadora-local',
    type: 'importadora',
    companyId: 'c-tecno',
    originBranchId: 'b-tecno-la-paz',
    buyer: { name: 'Rosa Villca', phone: '7712 4408', ci: '4408' },
    buyerCityId: 'la-paz',
    address: 'Calle 5 de Obrajes 120, La Paz',
    delivery: 'domicilio',
    lines: [
      {
        productId: 'tb-audifonos',
        name: 'Audífonos con cancelación',
        qty: 1,
        unitBob: 780,
        options: [],
      },
    ],
    subtotalBob: 780,
    deliveryBob: 10,
    totalBob: 790,
    state: 'esperando-rider',
    placedAt: '2026-08-15T12:44:00',
    promisedAt: '2026-08-15T15:30:00',
    assignments: [],
    custody: { kind: 'sucursal', branchId: 'b-tecno-la-paz', since: '2026-08-15T12:44:00' },
    threadId: 'th-2201',
  },
  {
    code: 'TO-2202',
    slug: 'to-2202',
    scenario: 'importadora-local',
    type: 'importadora',
    companyId: 'c-ale',
    originBranchId: 'b-ale-cochabamba',
    buyer: { name: 'Elsa Rocha', phone: '7644 9021', ci: '9021' },
    buyerCityId: 'cochabamba',
    address: 'Av. Pando 455, Cochabamba',
    delivery: 'domicilio',
    lines: [
      {
        productId: 'al-campera',
        name: 'Campera impermeable',
        qty: 1,
        unitBob: 320,
        options: ['Talla M'],
      },
      { productId: 'al-gorra', name: 'Gorra de lona', qty: 1, unitBob: 75, options: [] },
    ],
    subtotalBob: 395,
    deliveryBob: 10,
    totalBob: 405,
    state: 'en-camino',
    placedAt: '2026-08-15T11:50:00',
    promisedAt: '2026-08-15T13:30:00',
    assignments: [
      {
        leg: 'origen',
        riderId: 'r-lucia',
        branchId: 'b-ale-cochabamba',
        assignedAt: '2026-08-15T12:30:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-lucia', since: '2026-08-15T12:35:00' },
    threadId: 'th-2202',
  },
  {
    code: 'TO-2203',
    slug: 'to-2203',
    scenario: 'interurbano-domicilio',
    type: 'importadora',
    companyId: 'c-ale',
    originBranchId: 'b-ale-la-paz',
    destinationBranchId: 'b-ale-santa-cruz',
    buyer: { name: 'Marcela Áñez', phone: '7009 4417', ci: '4417' },
    buyerCityId: 'santa-cruz',
    address: 'Calle Los Cusis 310, Santa Cruz',
    delivery: 'domicilio',
    lines: [
      { productId: 'al-jean', name: 'Jean recto', qty: 2, unitBob: 210, options: ['Talla L'] },
      { productId: 'al-zapatilla', name: 'Zapatilla urbana', qty: 1, unitBob: 380, options: [] },
    ],
    subtotalBob: 800,
    deliveryBob: 45,
    totalBob: 845,
    state: 'esperando-carga',
    placedAt: '2026-08-15T10:12:00',
    promisedAt: '2026-08-17T18:00:00',
    assignments: [],
    custody: { kind: 'sucursal', branchId: 'b-ale-la-paz', since: '2026-08-15T10:12:00' },
    loadId: 'cg-3301',
    threadId: 'th-2203',
  },
  {
    code: 'TO-2204',
    slug: 'to-2204',
    scenario: 'interurbano-domicilio',
    type: 'importadora',
    companyId: 'c-tecno',
    originBranchId: 'b-tecno-cochabamba',
    destinationBranchId: 'b-tecno-la-paz',
    buyer: { name: 'Rosa Villca', phone: '7712 4408', ci: '4408' },
    buyerCityId: 'la-paz',
    address: 'Calle 5 de Obrajes 120, La Paz',
    delivery: 'domicilio',
    lines: [
      {
        productId: 'tb-celular-medio',
        name: 'Celular 128 GB',
        qty: 1,
        unitBob: 1890,
        options: ['Un año más de garantía'],
      },
    ],
    subtotalBob: 1890,
    deliveryBob: 50,
    totalBob: 1940,
    state: 'en-ruta-interurbana',
    placedAt: '2026-08-14T16:20:00',
    promisedAt: '2026-08-15T19:00:00',
    assignments: [
      {
        leg: 'interurbano',
        riderId: 'r-elias',
        branchId: 'b-tecno-cochabamba',
        assignedAt: '2026-08-15T07:20:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-elias', since: '2026-08-15T07:30:00' },
    loadId: 'cg-3302',
    threadId: 'th-2204',
  },
  {
    code: 'TO-2205',
    slug: 'to-2205',
    scenario: 'interurbano-domicilio',
    type: 'importadora',
    companyId: 'c-ale',
    originBranchId: 'b-ale-santa-cruz',
    destinationBranchId: 'b-ale-la-paz',
    buyer: { name: 'Rosa Villca', phone: '7712 4408', ci: '4408' },
    buyerCityId: 'la-paz',
    address: 'Calle 5 de Obrajes 120, La Paz',
    delivery: 'domicilio',
    lines: [
      { productId: 'al-mochila', name: 'Mochila 25 litros', qty: 2, unitBob: 245, options: [] },
      {
        productId: 'al-campera',
        name: 'Campera impermeable',
        qty: 1,
        unitBob: 320,
        options: ['Talla S'],
      },
    ],
    subtotalBob: 810,
    deliveryBob: 45,
    totalBob: 855,
    state: 'reparto-local',
    placedAt: '2026-08-13T15:40:00',
    promisedAt: '2026-08-15T14:30:00',
    assignments: [
      {
        leg: 'interurbano',
        riderId: 'r-hugo',
        branchId: 'b-ale-santa-cruz',
        assignedAt: '2026-08-14T06:30:00',
      },
      {
        leg: 'local',
        riderId: 'r-marco',
        branchId: 'b-ale-la-paz',
        assignedAt: '2026-08-15T12:50:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-marco', since: '2026-08-15T12:55:00' },
    loadId: 'cg-3303',
    threadId: 'th-2205',
  },
  {
    code: 'TO-2206',
    slug: 'to-2206',
    scenario: 'interurbano-sucursal',
    type: 'importadora',
    companyId: 'c-andes',
    originBranchId: 'b-andes-santa-cruz',
    destinationBranchId: 'b-andes-la-paz',
    buyer: { name: 'Julio Ramos', phone: '7188 2204', ci: '2204' },
    buyerCityId: 'la-paz',
    delivery: 'sucursal',
    lines: [
      {
        productId: 'an-casco',
        name: 'Casco integral certificado',
        qty: 1,
        unitBob: 540,
        options: ['Talla L'],
      },
      { productId: 'an-candado', name: 'Candado de disco', qty: 1, unitBob: 180, options: [] },
    ],
    subtotalBob: 720,
    deliveryBob: 0,
    totalBob: 720,
    state: 'listo-para-recojo',
    placedAt: '2026-08-13T11:05:00',
    promisedAt: '2026-08-15T12:00:00',
    assignments: [
      {
        leg: 'interurbano',
        riderId: 'r-elias',
        branchId: 'b-andes-santa-cruz',
        assignedAt: '2026-08-14T07:00:00',
      },
    ],
    custody: { kind: 'sucursal', branchId: 'b-andes-la-paz', since: '2026-08-15T09:15:00' },
    loadId: 'cg-3305',
    threadId: 'th-2206',
  },
  {
    code: 'TO-2207',
    slug: 'to-2207',
    scenario: 'interurbano-sucursal',
    type: 'importadora',
    companyId: 'c-ale',
    originBranchId: 'b-ale-la-paz',
    destinationBranchId: 'b-ale-cochabamba',
    buyer: { name: 'Wilson Zeballos', phone: '7455 3390', ci: '3390' },
    buyerCityId: 'cochabamba',
    delivery: 'sucursal',
    lines: [
      { productId: 'al-jean', name: 'Jean recto', qty: 1, unitBob: 210, options: ['Talla M'] },
    ],
    subtotalBob: 210,
    deliveryBob: 0,
    totalBob: 210,
    state: 'entregado',
    placedAt: '2026-08-11T09:30:00',
    promisedAt: '2026-08-13T12:00:00',
    assignments: [
      {
        leg: 'interurbano',
        riderId: 'r-hugo',
        branchId: 'b-ale-la-paz',
        assignedAt: '2026-08-12T06:20:00',
      },
    ],
    custody: { kind: 'sucursal', branchId: 'b-ale-cochabamba', since: '2026-08-13T08:40:00' },
    loadId: 'cg-3304',
    threadId: 'th-2207',
    scannedAt: '2026-08-13T17:22:00',
    scannedBy: 'b-ale-cochabamba',
  },
  {
    code: 'TO-2208',
    slug: 'to-2208',
    scenario: 'interurbano-domicilio',
    type: 'importadora',
    companyId: 'c-ale',
    originBranchId: 'b-ale-la-paz',
    destinationBranchId: 'b-ale-cochabamba',
    buyer: { name: 'Elsa Rocha', phone: '7644 9021', ci: '9021' },
    buyerCityId: 'cochabamba',
    address: 'Av. Pando 455, Cochabamba',
    delivery: 'domicilio',
    lines: [
      { productId: 'al-gorra', name: 'Gorra de lona', qty: 2, unitBob: 75, options: [] },
      { productId: 'al-mochila', name: 'Mochila 25 litros', qty: 1, unitBob: 245, options: [] },
    ],
    subtotalBob: 395,
    deliveryBob: 40,
    totalBob: 435,
    state: 'entregado',
    placedAt: '2026-08-11T10:15:00',
    promisedAt: '2026-08-13T16:00:00',
    assignments: [
      {
        leg: 'interurbano',
        riderId: 'r-hugo',
        branchId: 'b-ale-la-paz',
        assignedAt: '2026-08-12T06:20:00',
      },
      {
        leg: 'local',
        riderId: 'r-lucia',
        branchId: 'b-ale-cochabamba',
        assignedAt: '2026-08-13T14:00:00',
      },
    ],
    custody: { kind: 'rider', riderId: 'r-lucia', since: '2026-08-13T14:05:00' },
    loadId: 'cg-3304',
    threadId: 'th-2208',
    scannedAt: '2026-08-13T15:12:00',
    scannedBy: 'r-lucia',
    review: {
      stars: 4,
      text: 'Llegó bien, un día después de lo que decía.',
      at: '2026-08-14T09:00:00',
    },
  },
];

export const COUPONS: readonly Coupon[] = [
  {
    code: 'COPA10',
    companyId: 'c-copacabana',
    label: 'Bs 10 de descuento en combos',
    discountBob: 10,
    uses: 128,
    limit: 300,
    active: true,
    until: '2026-09-30',
  },
  {
    code: 'SALTENA2X1',
    companyId: 'c-copacabana',
    label: 'Segunda salteña a mitad de precio',
    discountBob: 5,
    uses: 300,
    limit: 300,
    active: false,
    until: '2026-08-14',
  },
  {
    code: 'ORIENTAL15',
    companyId: 'c-oriental',
    label: 'Bs 15 en tu primer majadito',
    discountBob: 15,
    uses: 42,
    limit: 200,
    active: true,
    until: '2026-10-15',
  },
  {
    code: 'ALEENVIO',
    companyId: 'c-ale',
    label: 'Envío interurbano a mitad de precio',
    discountBob: 22,
    uses: 61,
    limit: 150,
    active: true,
    until: '2026-09-15',
  },
];

export const SETTLEMENTS: readonly Settlement[] = [
  {
    id: 'lq-30',
    companyId: 'c-copacabana',
    branchId: 'b-copacabana-miraflores',
    period: 'Agosto, primera quincena',
    orders: 412,
    grossBob: 38940,
    commissionBob: 5841,
    netBob: 33099,
    paidAt: '2026-08-16',
  },
  {
    id: 'lq-31',
    companyId: 'c-copacabana',
    branchId: 'b-copacabana-sopocachi',
    period: 'Agosto, primera quincena',
    orders: 268,
    grossBob: 24160,
    commissionBob: 3624,
    netBob: 20536,
    paidAt: '2026-08-16',
  },
  {
    id: 'lq-32',
    companyId: 'c-copacabana',
    branchId: 'b-copacabana-miraflores',
    period: 'Julio, segunda quincena',
    orders: 389,
    grossBob: 36110,
    commissionBob: 5417,
    netBob: 30693,
    paidAt: '2026-08-01',
  },
  {
    id: 'lq-33',
    companyId: 'c-ale',
    branchId: 'b-ale-la-paz',
    period: 'Agosto, primera quincena',
    orders: 96,
    grossBob: 41280,
    commissionBob: 6192,
    netBob: 35088,
  },
  {
    id: 'lq-34',
    companyId: 'c-ale',
    branchId: 'b-ale-santa-cruz',
    period: 'Agosto, primera quincena',
    orders: 74,
    grossBob: 33150,
    commissionBob: 4973,
    netBob: 28177,
  },
];
