import { Addon, Product, Variant } from './marketplace.model';

const SIZES: readonly Variant[] = [
  { id: 'personal', label: 'Personal', deltaBob: 0 },
  { id: 'familiar', label: 'Familiar', deltaBob: 28 },
];

const EXTRAS: readonly Addon[] = [
  { id: 'papas', label: 'Papas extra', priceBob: 8 },
  { id: 'llajua', label: 'Llajua de la casa', priceBob: 3 },
  { id: 'gaseosa', label: 'Gaseosa 500 ml', priceBob: 10 },
];

export const PRODUCTS: readonly Product[] = [
  {
    id: 'pc-broaster-1-4',
    merchantSlug: 'pollos-copacabana',
    category: 'Pollo',
    name: 'Broaster 1/4 con papas',
    description: 'Presa de pollo broaster, papas fritas y ensalada de la casa.',
    priceBob: 32,
    available: true,
    featured: true,
    soldThisMonth: 412,
    variants: [],
    addons: EXTRAS,
  },
  {
    id: 'pc-combo-familiar',
    merchantSlug: 'pollos-copacabana',
    category: 'Combos',
    name: 'Combo familiar 8 presas',
    description: 'Ocho presas, papas grandes, ensalada y gaseosa de dos litros.',
    priceBob: 145,
    available: true,
    featured: true,
    soldThisMonth: 168,
    variants: [],
    addons: EXTRAS,
  },
  {
    id: 'pc-saltena-carne',
    merchantSlug: 'pollos-copacabana',
    category: 'Salteñas',
    name: 'Salteña de carne',
    description: 'Jugosa, con aceituna y huevo. Hasta agotar la hornada.',
    priceBob: 9,
    available: true,
    featured: false,
    soldThisMonth: 903,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-saltena-pollo',
    merchantSlug: 'pollos-copacabana',
    category: 'Salteñas',
    name: 'Salteña de pollo',
    description: 'Con papa, arveja y un toque de ají amarillo.',
    priceBob: 9,
    available: false,
    featured: false,
    soldThisMonth: 654,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-sopa-mani',
    merchantSlug: 'pollos-copacabana',
    category: 'Pollo',
    name: 'Sopa de maní',
    description: 'Maní molido a piedra, carne y papas fritas encima.',
    priceBob: 25,
    available: true,
    featured: false,
    soldThisMonth: 288,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-gaseosa',
    merchantSlug: 'pollos-copacabana',
    category: 'Bebidas',
    name: 'Gaseosa 2 litros',
    description: 'Fría, de la marca que haya en heladera.',
    priceBob: 18,
    available: true,
    featured: false,
    soldThisMonth: 341,
    variants: [],
    addons: [],
  },
  {
    id: 'pc-mocochinchi',
    merchantSlug: 'pollos-copacabana',
    category: 'Bebidas',
    name: 'Mocochinchi',
    description: 'Refresco de durazno pelado, servido helado.',
    priceBob: 8,
    available: true,
    featured: false,
    soldThisMonth: 219,
    variants: [],
    addons: [],
  },
  {
    id: 'so-majadito',
    merchantSlug: 'sabor-oriental',
    category: 'Almuerzos',
    name: 'Majadito batido',
    description: 'Arroz batido con charque, huevo frito y plátano.',
    priceBob: 38,
    available: true,
    featured: true,
    soldThisMonth: 264,
    variants: [],
    addons: [],
  },
  {
    id: 'so-keperi',
    merchantSlug: 'sabor-oriental',
    category: 'Parrilla',
    name: 'Keperí a la olla',
    description: 'Carne de tapa cocida lento, con yuca y arroz.',
    priceBob: 52,
    available: true,
    featured: true,
    soldThisMonth: 141,
    variants: [],
    addons: [],
  },
  {
    id: 'so-cunape',
    merchantSlug: 'sabor-oriental',
    category: 'Horneados',
    name: 'Cuñapé por seis',
    description: 'Recién horneados, con queso chaqueño.',
    priceBob: 20,
    available: true,
    featured: false,
    soldThisMonth: 398,
    variants: [],
    addons: [],
  },
  {
    id: 'dr-silpancho',
    merchantSlug: 'la-cocina-de-dona-rita',
    category: 'Platos fuertes',
    name: 'Silpancho cochabambino',
    description: 'Carne apanada, arroz, papa y huevo frito.',
    priceBob: 42,
    available: true,
    featured: true,
    soldThisMonth: 377,
    variants: [],
    addons: [],
  },
  {
    id: 'dr-pique',
    merchantSlug: 'la-cocina-de-dona-rita',
    category: 'Platos fuertes',
    name: 'Pique macho para dos',
    description: 'Carne, salchicha, papas fritas y locoto de verdad.',
    priceBob: 78,
    available: true,
    featured: true,
    soldThisMonth: 205,
    variants: [],
    addons: [],
  },
  {
    id: 'dr-chicharron',
    merchantSlug: 'la-cocina-de-dona-rita',
    category: 'Almuerzos',
    name: 'Chicharrón de cerdo',
    description: 'Con mote, chuño y ensalada criolla.',
    priceBob: 55,
    available: true,
    featured: false,
    soldThisMonth: 162,
    variants: [],
    addons: [],
  },
  {
    id: 'dr-flan',
    merchantSlug: 'la-cocina-de-dona-rita',
    category: 'Postres',
    name: 'Flan de la casa',
    description: 'Caramelo hecho a diario.',
    priceBob: 14,
    available: true,
    featured: false,
    soldThisMonth: 122,
    variants: [],
    addons: [],
  },
  {
    id: 'si-roll-illimani',
    merchantSlug: 'sushi-illimani',
    category: 'Rolls',
    name: 'Roll Illimani',
    description: 'Salmón, palta y queso crema, cubierto en sésamo.',
    priceBob: 58,
    available: true,
    featured: true,
    soldThisMonth: 231,
    variants: [],
    addons: [],
  },
  {
    id: 'si-gyoza',
    merchantSlug: 'sushi-illimani',
    category: 'Entradas',
    name: 'Gyozas por seis',
    description: 'Rellenas de cerdo y cebollín, selladas a la plancha.',
    priceBob: 34,
    available: true,
    featured: false,
    soldThisMonth: 148,
    variants: [],
    addons: [],
  },
  {
    id: 'si-ramen',
    merchantSlug: 'sushi-illimani',
    category: 'Calientes',
    name: 'Ramen de cerdo',
    description: 'Caldo de doce horas, huevo marinado y panceta.',
    priceBob: 62,
    available: true,
    featured: true,
    soldThisMonth: 96,
    variants: [],
    addons: [],
  },
  {
    id: 'eh-margarita',
    merchantSlug: 'pizzeria-el-horno',
    category: 'Pizzas',
    name: 'Pizza margarita',
    description: 'Tomate San Marzano, mozzarella fior di latte y albahaca.',
    priceBob: 55,
    available: true,
    featured: true,
    soldThisMonth: 302,
    variants: SIZES,
    addons: [{ id: 'borde', label: 'Borde relleno de queso', priceBob: 15 }],
  },
  {
    id: 'eh-pepperoni',
    merchantSlug: 'pizzeria-el-horno',
    category: 'Pizzas',
    name: 'Pizza pepperoni',
    description: 'Doble pepperoni y orégano de Vallegrande.',
    priceBob: 68,
    available: true,
    featured: true,
    soldThisMonth: 274,
    variants: SIZES,
    addons: [{ id: 'borde', label: 'Borde relleno de queso', priceBob: 15 }],
  },
  {
    id: 'eh-focaccia',
    merchantSlug: 'pizzeria-el-horno',
    category: 'Entradas',
    name: 'Focaccia de romero',
    description: 'Masa madre, aceite de oliva y sal gruesa.',
    priceBob: 26,
    available: true,
    featured: false,
    soldThisMonth: 118,
    variants: [],
    addons: [],
  },
  {
    id: 'bt-clasica',
    merchantSlug: 'burger-terminal',
    category: 'Hamburguesas',
    name: 'Hamburguesa clásica',
    description: 'Carne de 150 g, cheddar, lechuga y tomate.',
    priceBob: 35,
    available: true,
    featured: true,
    soldThisMonth: 388,
    variants: [{ id: 'doble', label: 'Doble carne', deltaBob: 18 }],
    addons: [{ id: 'bacon', label: 'Tocino crocante', priceBob: 9 }],
  },
  {
    id: 'bt-papas',
    merchantSlug: 'burger-terminal',
    category: 'Acompañamientos',
    name: 'Papas rústicas',
    description: 'Con piel, sal de Uyuni y alioli.',
    priceBob: 18,
    available: true,
    featured: false,
    soldThisMonth: 291,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-desayuno',
    merchantSlug: 'cafe-sucre',
    category: 'Desayunos',
    name: 'Desayuno sucrense',
    description: 'Café con leche, pan de tres puntas, huevos y fruta.',
    priceBob: 32,
    available: true,
    featured: true,
    soldThisMonth: 254,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-torta',
    merchantSlug: 'cafe-sucre',
    category: 'Panadería',
    name: 'Torta de chocolate',
    description: 'Porción generosa, con cacao de Alto Beni.',
    priceBob: 18,
    available: true,
    featured: false,
    soldThisMonth: 176,
    variants: [],
    addons: [],
  },
  {
    id: 'cs-capuchino',
    merchantSlug: 'cafe-sucre',
    category: 'Café',
    name: 'Capuchino',
    description: 'Café de yungas tostado en la casa.',
    priceBob: 16,
    available: true,
    featured: false,
    soldThisMonth: 512,
    variants: [],
    addons: [],
  },
  {
    id: 'vf-bowl',
    merchantSlug: 'vegetal-y-fresco',
    category: 'Bowls',
    name: 'Bowl de quinua',
    description: 'Quinua real, palta, tomate cherry y semillas.',
    priceBob: 44,
    available: true,
    featured: true,
    soldThisMonth: 133,
    variants: [],
    addons: [],
  },
  {
    id: 'vf-jugo',
    merchantSlug: 'vegetal-y-fresco',
    category: 'Jugos',
    name: 'Jugo verde prensado',
    description: 'Apio, manzana, jengibre y limón.',
    priceBob: 22,
    available: true,
    featured: false,
    soldThisMonth: 208,
    variants: [],
    addons: [],
  },
  {
    id: 'ia-casaca-jean',
    merchantSlug: 'importadora-ale',
    category: 'Ropa',
    name: 'Casaca de jean',
    description: 'Corte recto, tallas S a XL. Stock en El Alto.',
    priceBob: 180,
    available: true,
    featured: true,
    soldThisMonth: 64,
    variants: [
      { id: 's', label: 'Talla S', deltaBob: 0 },
      { id: 'm', label: 'Talla M', deltaBob: 0 },
      { id: 'l', label: 'Talla L', deltaBob: 0 },
      { id: 'xl', label: 'Talla XL', deltaBob: 10 },
    ],
    addons: [],
  },
  {
    id: 'ia-polera-algodon',
    merchantSlug: 'importadora-ale',
    category: 'Ropa',
    name: 'Polera de algodón',
    description: 'Algodón peinado, seis colores disponibles.',
    priceBob: 75,
    available: true,
    featured: true,
    soldThisMonth: 212,
    variants: [],
    addons: [],
  },
  {
    id: 'ia-zapatilla-urbana',
    merchantSlug: 'importadora-ale',
    category: 'Calzado',
    name: 'Zapatilla urbana',
    description: 'Suela de goma, numeración 36 a 44.',
    priceBob: 260,
    available: true,
    featured: false,
    soldThisMonth: 88,
    variants: [],
    addons: [],
  },
  {
    id: 'ia-mochila',
    merchantSlug: 'importadora-ale',
    category: 'Accesorios',
    name: 'Mochila impermeable',
    description: 'Veinticinco litros, compartimento para laptop.',
    priceBob: 145,
    available: false,
    featured: false,
    soldThisMonth: 41,
    variants: [],
    addons: [],
  },
  {
    id: 'ti-celular-x9',
    merchantSlug: 'tecno-import',
    category: 'Celulares',
    name: 'Celular X9 128 GB',
    description: 'Pantalla de 6,7 pulgadas, batería de 5000 mAh.',
    priceBob: 1890,
    available: true,
    featured: true,
    soldThisMonth: 37,
    variants: [],
    addons: [],
  },
  {
    id: 'ti-audifonos',
    merchantSlug: 'tecno-import',
    category: 'Audio',
    name: 'Audífonos inalámbricos',
    description: 'Cancelación de ruido y estuche de carga.',
    priceBob: 320,
    available: true,
    featured: true,
    soldThisMonth: 126,
    variants: [],
    addons: [],
  },
  {
    id: 'ti-cargador',
    merchantSlug: 'tecno-import',
    category: 'Accesorios',
    name: 'Cargador rápido 65 W',
    description: 'Dos puertos, compatible con laptop.',
    priceBob: 180,
    available: true,
    featured: false,
    soldThisMonth: 94,
    variants: [],
    addons: [],
  },
  {
    id: 'hm-olla-presion',
    merchantSlug: 'hogar-y-mas',
    category: 'Cocina',
    name: 'Olla a presión de 6 litros',
    description: 'Acero inoxidable con doble válvula de seguridad.',
    priceBob: 420,
    available: true,
    featured: true,
    soldThisMonth: 29,
    variants: [],
    addons: [],
  },
  {
    id: 'hm-organizador',
    merchantSlug: 'hogar-y-mas',
    category: 'Organización',
    name: 'Organizador plegable',
    description: 'Tela reforzada, tres compartimentos.',
    priceBob: 95,
    available: true,
    featured: false,
    soldThisMonth: 61,
    variants: [],
    addons: [],
  },
  {
    id: 'mr-llanta-moto',
    merchantSlug: 'moto-repuestos-bolivia',
    category: 'Llantas',
    name: 'Llanta 110/90-17',
    description: 'Dibujo mixto, para calle y ripio.',
    priceBob: 340,
    available: true,
    featured: true,
    soldThisMonth: 52,
    variants: [],
    addons: [],
  },
  {
    id: 'mr-casco',
    merchantSlug: 'moto-repuestos-bolivia',
    category: 'Cascos',
    name: 'Casco integral certificado',
    description: 'Visera antiempañante, tallas M a XL.',
    priceBob: 480,
    available: true,
    featured: true,
    soldThisMonth: 38,
    variants: [],
    addons: [],
  },
  {
    id: 'bi-serum',
    merchantSlug: 'belleza-import',
    category: 'Cuidado facial',
    name: 'Sérum de vitamina C',
    description: 'Treinta mililitros, con ácido hialurónico.',
    priceBob: 210,
    available: true,
    featured: true,
    soldThisMonth: 143,
    variants: [],
    addons: [],
  },
  {
    id: 'bi-secador',
    merchantSlug: 'belleza-import',
    category: 'Cabello',
    name: 'Secador iónico',
    description: 'Dos mil vatios, tres temperaturas.',
    priceBob: 390,
    available: true,
    featured: false,
    soldThisMonth: 47,
    variants: [],
    addons: [],
  },
  {
    id: 'da-zapatilla-trail',
    merchantSlug: 'deportes-andinos',
    category: 'Calzado',
    name: 'Zapatilla de trail',
    description: 'Suela con taco profundo para cerro.',
    priceBob: 520,
    available: true,
    featured: true,
    soldThisMonth: 33,
    variants: [],
    addons: [],
  },
  {
    id: 'da-mochila-40',
    merchantSlug: 'deportes-andinos',
    category: 'Mochilas',
    name: 'Mochila de montaña 40 L',
    description: 'Con funda de lluvia y arnés regulable.',
    priceBob: 610,
    available: true,
    featured: false,
    soldThisMonth: 21,
    variants: [],
    addons: [],
  },
];
