import { ReputationTally } from './reputation.model';

export const REPUTATION_HISTORY: readonly ReputationTally[] = [
  { subjectId: 'r-marco', fact: 'entrega-a-tiempo', count: 186 },
  { subjectId: 'r-marco', fact: 'entrega-tarde', count: 7 },
  { subjectId: 'r-marco', fact: 'reclutamiento-cumplido', count: 6 },
  { subjectId: 'r-noemi', fact: 'entrega-a-tiempo', count: 142 },
  { subjectId: 'r-noemi', fact: 'entrega-tarde', count: 3 },
  { subjectId: 'r-noemi', fact: 'reclutamiento-cumplido', count: 5 },
  { subjectId: 'r-ivan', fact: 'entrega-a-tiempo', count: 88 },
  { subjectId: 'r-ivan', fact: 'entrega-tarde', count: 6 },
  { subjectId: 'r-ivan', fact: 'reclutamiento-cumplido', count: 3 },
  { subjectId: 'r-gabriela', fact: 'entrega-a-tiempo', count: 121 },
  { subjectId: 'r-gabriela', fact: 'entrega-tarde', count: 5 },
  { subjectId: 'r-gabriela', fact: 'reclutamiento-cumplido', count: 4 },
  { subjectId: 'r-rene', fact: 'entrega-a-tiempo', count: 41 },
  { subjectId: 'r-rene', fact: 'entrega-tarde', count: 13 },
  { subjectId: 'r-rene', fact: 'reclutamiento-cumplido', count: 1 },
  { subjectId: 'r-rene', fact: 'reclutamiento-abandonado', count: 3 },
  { subjectId: 'r-lucia', fact: 'entrega-a-tiempo', count: 97 },
  { subjectId: 'r-lucia', fact: 'entrega-tarde', count: 7 },
  { subjectId: 'r-lucia', fact: 'reclutamiento-cumplido', count: 3 },
  { subjectId: 'r-alvaro', fact: 'entrega-a-tiempo', count: 64 },
  { subjectId: 'r-alvaro', fact: 'entrega-tarde', count: 8 },
  { subjectId: 'r-alvaro', fact: 'reclutamiento-cumplido', count: 2 },
  { subjectId: 'r-alvaro', fact: 'reclutamiento-abandonado', count: 1 },
  { subjectId: 'r-rosario', fact: 'entrega-a-tiempo', count: 73 },
  { subjectId: 'r-rosario', fact: 'entrega-tarde', count: 2 },
  { subjectId: 'r-rosario', fact: 'reclutamiento-cumplido', count: 4 },
  { subjectId: 'r-hugo', fact: 'carga-entregada', count: 58 },
  { subjectId: 'r-hugo', fact: 'entrega-tarde', count: 3 },
  { subjectId: 'r-hugo', fact: 'reclutamiento-cumplido', count: 3 },

  { subjectId: 'b-copacabana-miraflores', fact: 'pedido-despachado', count: 812 },
  { subjectId: 'b-copacabana-miraflores', fact: 'pedido-rechazado', count: 34 },
  { subjectId: 'b-copacabana-miraflores', fact: 'pedido-sin-rider', count: 11 },
  { subjectId: 'b-copacabana-sopocachi', fact: 'pedido-despachado', count: 604 },
  { subjectId: 'b-copacabana-sopocachi', fact: 'pedido-rechazado', count: 41 },
  { subjectId: 'b-copacabana-sopocachi', fact: 'pedido-sin-rider', count: 18 },
  { subjectId: 'b-copacabana-cala-cala', fact: 'pedido-despachado', count: 388 },
  { subjectId: 'b-copacabana-cala-cala', fact: 'pedido-rechazado', count: 44 },
  { subjectId: 'b-copacabana-cala-cala', fact: 'pedido-sin-rider', count: 22 },
  { subjectId: 'b-oriental-equipetrol', fact: 'pedido-despachado', count: 731 },
  { subjectId: 'b-oriental-equipetrol', fact: 'pedido-rechazado', count: 26 },
  { subjectId: 'b-oriental-equipetrol', fact: 'pedido-sin-rider', count: 9 },
  { subjectId: 'b-oriental-norte', fact: 'pedido-despachado', count: 455 },
  { subjectId: 'b-oriental-norte', fact: 'pedido-rechazado', count: 33 },
  { subjectId: 'b-oriental-norte', fact: 'pedido-sin-rider', count: 14 },
  { subjectId: 'b-illimani-san-miguel', fact: 'pedido-despachado', count: 549 },
  { subjectId: 'b-illimani-san-miguel', fact: 'pedido-rechazado', count: 21 },
  { subjectId: 'b-illimani-san-miguel', fact: 'pedido-sin-rider', count: 8 },
  { subjectId: 'b-cafe-sucre-centro', fact: 'pedido-despachado', count: 402 },
  { subjectId: 'b-cafe-sucre-centro', fact: 'pedido-rechazado', count: 29 },
  { subjectId: 'b-cafe-sucre-centro', fact: 'pedido-sin-rider', count: 12 },
  { subjectId: 'b-cafe-sucre-recoleta', fact: 'pedido-despachado', count: 268 },
  { subjectId: 'b-cafe-sucre-recoleta', fact: 'pedido-rechazado', count: 19 },
  { subjectId: 'b-cafe-sucre-recoleta', fact: 'pedido-sin-rider', count: 7 },
  { subjectId: 'b-ale-la-paz', fact: 'pedido-despachado', count: 517 },
  { subjectId: 'b-ale-la-paz', fact: 'pedido-rechazado', count: 22 },
  { subjectId: 'b-ale-la-paz', fact: 'pedido-sin-rider', count: 10 },
  { subjectId: 'b-ale-santa-cruz', fact: 'pedido-despachado', count: 644 },
  { subjectId: 'b-ale-santa-cruz', fact: 'pedido-rechazado', count: 25 },
  { subjectId: 'b-ale-santa-cruz', fact: 'pedido-sin-rider', count: 12 },
  { subjectId: 'b-ale-cochabamba', fact: 'pedido-despachado', count: 296 },
  { subjectId: 'b-ale-cochabamba', fact: 'pedido-rechazado', count: 17 },
  { subjectId: 'b-ale-cochabamba', fact: 'pedido-sin-rider', count: 9 },
  { subjectId: 'b-andes-santa-cruz', fact: 'pedido-despachado', count: 471 },
  { subjectId: 'b-andes-santa-cruz', fact: 'pedido-rechazado', count: 30 },
  { subjectId: 'b-andes-santa-cruz', fact: 'pedido-sin-rider', count: 15 },
  { subjectId: 'b-andes-la-paz', fact: 'pedido-despachado', count: 383 },
  { subjectId: 'b-andes-la-paz', fact: 'pedido-rechazado', count: 27 },
  { subjectId: 'b-andes-la-paz', fact: 'pedido-sin-rider', count: 13 },
  { subjectId: 'b-andes-sucre', fact: 'pedido-despachado', count: 214 },
  { subjectId: 'b-andes-sucre', fact: 'pedido-rechazado', count: 18 },
  { subjectId: 'b-andes-sucre', fact: 'pedido-sin-rider', count: 11 },
  { subjectId: 'b-tecno-cochabamba', fact: 'pedido-despachado', count: 336 },
  { subjectId: 'b-tecno-cochabamba', fact: 'pedido-rechazado', count: 24 },
  { subjectId: 'b-tecno-cochabamba', fact: 'pedido-sin-rider', count: 10 },
  { subjectId: 'b-tecno-la-paz', fact: 'pedido-despachado', count: 259 },
  { subjectId: 'b-tecno-la-paz', fact: 'pedido-rechazado', count: 20 },
  { subjectId: 'b-tecno-la-paz', fact: 'pedido-sin-rider', count: 8 },
  { subjectId: 'b-yungas-oruro', fact: 'pedido-despachado', count: 118 },
  { subjectId: 'b-yungas-oruro', fact: 'pedido-rechazado', count: 39 },
  { subjectId: 'b-yungas-oruro', fact: 'pedido-sin-rider', count: 21 },
  { subjectId: 'b-yungas-la-paz', fact: 'pedido-despachado', count: 173 },
  { subjectId: 'b-yungas-la-paz', fact: 'pedido-rechazado', count: 16 },
  { subjectId: 'b-yungas-la-paz', fact: 'pedido-sin-rider', count: 6 },

  { subjectId: '7712 4408', fact: 'recibido-a-la-primera', count: 46 },
  { subjectId: '7712 4408', fact: 'recojo-a-tiempo', count: 8 },
  { subjectId: '7712 4408', fact: 'recojo-abandonado', count: 1 },
  { subjectId: '7712 4408', fact: 'direccion-incorrecta', count: 1 },
  { subjectId: '7008 3312', fact: 'recibido-a-la-primera', count: 22 },
  { subjectId: '7355 8890', fact: 'recibido-a-la-primera', count: 14 },
  { subjectId: '7355 8890', fact: 'recojo-abandonado', count: 2 },
  { subjectId: '7112 5540', fact: 'recibido-a-la-primera', count: 31 },
  { subjectId: '7112 5540', fact: 'recojo-a-tiempo', count: 5 },
];
