import { Payout, Rider } from './riders.model';

export const RIDERS: readonly Rider[] = [
  {
    id: 'r-marco',
    slug: 'marco-quispe',
    name: 'Marco Quispe',
    plate: '3421 KZP',
    vehicle: 'moto',
    cityId: 'la-paz',
    zones: ['Miraflores', 'Sopocachi', 'Centro'],
    rating: 4.8,
    tripsDone: 1240,
    onTimePct: 96,
    online: true,
    ratePerTripBob: 15,
    account: 'BNB ····4471',
    payoutMethod: 'tarjeta',
    card: { brand: 'Visa', last4: '4471', holder: 'Marco Quispe', expires: '09/29' },
    phone: '7712 6690',
  },
  {
    id: 'r-noemi',
    slug: 'noemi-flores',
    name: 'Noemí Flores',
    plate: '2287 LMR',
    vehicle: 'moto',
    cityId: 'la-paz',
    zones: ['San Miguel', 'Obrajes'],
    rating: 4.9,
    tripsDone: 980,
    onTimePct: 98,
    online: true,
    ratePerTripBob: 16,
    account: 'BCP ····1180',
    payoutMethod: 'automatico',
    phone: '7365 4402',
  },
  {
    id: 'r-ivan',
    slug: 'ivan-mamani',
    name: 'Iván Mamani',
    plate: '1904 HTQ',
    vehicle: 'auto',
    cityId: 'la-paz',
    zones: ['Centro', 'Obrajes', 'Sopocachi'],
    rating: 4.6,
    tripsDone: 612,
    onTimePct: 92,
    online: false,
    ratePerTripBob: 22,
    account: 'Unión ····8830',
    payoutMethod: 'automatico',
    phone: '6884 2213',
  },
  {
    id: 'r-gabriela',
    slug: 'gabriela-suarez',
    name: 'Gabriela Suárez',
    plate: '5560 PQA',
    vehicle: 'moto',
    cityId: 'santa-cruz',
    zones: ['Equipetrol', 'Norte', 'Centro'],
    rating: 4.7,
    tripsDone: 1105,
    onTimePct: 94,
    online: true,
    ratePerTripBob: 18,
    account: 'BNB ····2204',
    payoutMethod: 'automatico',
    phone: '7008 9911',
  },
  {
    id: 'r-rene',
    slug: 'rene-justiniano',
    name: 'René Justiniano',
    plate: '4412 TDS',
    vehicle: 'moto',
    cityId: 'santa-cruz',
    zones: ['Plan Tres Mil', 'Centro'],
    rating: 4.4,
    tripsDone: 488,
    onTimePct: 89,
    online: true,
    ratePerTripBob: 17,
    account: 'BCP ····7742',
    payoutMethod: 'automatico',
    phone: '7112 3388',
  },
  {
    id: 'r-lucia',
    slug: 'lucia-vega',
    name: 'Lucía Vega',
    plate: '8873 RRM',
    vehicle: 'moto',
    cityId: 'cochabamba',
    zones: ['Cala Cala', 'Centro', 'Queru Queru'],
    rating: 4.8,
    tripsDone: 742,
    onTimePct: 97,
    online: true,
    ratePerTripBob: 15,
    account: 'Unión ····5519',
    payoutMethod: 'automatico',
    phone: '7644 1205',
  },
  {
    id: 'r-alvaro',
    slug: 'alvaro-terceros',
    name: 'Álvaro Terceros',
    plate: '6640 NJC',
    vehicle: 'auto',
    cityId: 'sucre',
    zones: ['Centro', 'Recoleta'],
    rating: 4.5,
    tripsDone: 355,
    onTimePct: 91,
    online: false,
    ratePerTripBob: 20,
    account: 'BNB ····6031',
    payoutMethod: 'automatico',
    phone: '7291 7744',
  },
  {
    id: 'r-rosario',
    slug: 'rosario-colque',
    name: 'Rosario Colque',
    plate: '9925 WBB',
    vehicle: 'moto',
    cityId: 'oruro',
    zones: ['Centro', 'Sud'],
    rating: 4.6,
    tripsDone: 402,
    onTimePct: 93,
    online: true,
    ratePerTripBob: 14,
    account: 'BCP ····3318',
    payoutMethod: 'automatico',
    phone: '7355 6602',
  },
  {
    id: 'r-hugo',
    slug: 'hugo-barrientos',
    name: 'Hugo Barrientos',
    plate: '1150 CMX',
    vehicle: 'camion',
    cityId: 'la-paz',
    zones: ['Interurbano'],
    rating: 4.7,
    tripsDone: 188,
    onTimePct: 95,
    online: true,
    ratePerTripBob: 240,
    account: 'BNB ····9004',
    payoutMethod: 'automatico',
    phone: '7188 4471',
  },
  {
    id: 'r-elias',
    slug: 'elias-poma',
    name: 'Elías Poma',
    plate: '7730 GFV',
    vehicle: 'camion',
    cityId: 'santa-cruz',
    zones: ['Interurbano'],
    rating: 4.5,
    tripsDone: 142,
    onTimePct: 90,
    online: false,
    ratePerTripBob: 260,
    account: 'Unión ····2277',
    payoutMethod: 'automatico',
    phone: '7444 0813',
  },
];

export const PAYOUTS: readonly Payout[] = [
  { day: '2026-08-10', label: 'Lunes', trips: 9, earnBob: 138 },
  { day: '2026-08-11', label: 'Martes', trips: 12, earnBob: 184 },
  { day: '2026-08-12', label: 'Miércoles', trips: 7, earnBob: 106 },
  { day: '2026-08-13', label: 'Jueves', trips: 14, earnBob: 214 },
  { day: '2026-08-14', label: 'Viernes', trips: 16, earnBob: 248 },
  { day: '2026-08-15', label: 'Sábado', trips: 11, earnBob: 170 },
];
