import { Branch, Carrier, Manifest, Milestone, Shipment, Tariff } from './shipping.model';

export const CARRIERS: readonly Carrier[] = [
  {
    id: 'bolivar',
    name: 'Flota Bolívar',
    departures: ['14:00', '19:00', '22:30'],
    branches: ['lp-terminal', 'scz-bimodal', 'cbba-terminal'],
  },
  {
    id: 'illimani',
    name: 'Trans Illimani',
    departures: ['08:00', '16:30'],
    branches: ['lp-terminal', 'oru-terminal'],
  },
  {
    id: 'copacabana',
    name: 'Expreso Copacabana',
    departures: ['07:30', '20:00'],
    branches: ['lp-terminal', 'scz-bimodal'],
  },
];

export const BRANCHES: readonly Branch[] = [
  {
    id: 'lp-terminal',
    carrierId: 'bolivar',
    city: 'La Paz',
    name: 'Bolívar · Terminal La Paz',
    address: 'Av. Perú 1780, Terminal de Buses',
    window: 'Lunes a domingo, 06:00 a 22:00',
    desk: 'Ventanilla 3',
  },
  {
    id: 'scz-bimodal',
    carrierId: 'bolivar',
    city: 'Santa Cruz',
    name: 'Bolívar · Terminal Bimodal',
    address: 'Av. Brasil esquina Tercer Anillo',
    window: 'Lunes a domingo, 06:00 a 23:00',
    desk: 'Ventanilla 7',
  },
  {
    id: 'cbba-terminal',
    carrierId: 'bolivar',
    city: 'Cochabamba',
    name: 'Bolívar · Terminal Cochabamba',
    address: 'Av. Ayacucho final, Terminal de Buses',
    window: 'Lunes a domingo, 06:30 a 22:00',
    desk: 'Ventanilla 2',
  },
  {
    id: 'oru-terminal',
    carrierId: 'illimani',
    city: 'Oruro',
    name: 'Illimani · Terminal Oruro',
    address: 'Calle Bakovic 1, Terminal de Buses',
    window: 'Lunes a sábado, 07:00 a 21:00',
    desk: 'Ventanilla 1',
  },
];

export const TARIFFS: readonly Tariff[] = [
  {
    fromCity: 'La Paz',
    toCity: 'Santa Cruz',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 50,
    pickupBob: 15,
    hours: 10,
  },
  {
    fromCity: 'La Paz',
    toCity: 'Cochabamba',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 40,
    pickupBob: 15,
    hours: 7,
  },
  {
    fromCity: 'La Paz',
    toCity: 'Oruro',
    carrierId: 'illimani',
    maxKg: 5,
    freightBob: 35,
    pickupBob: 15,
    hours: 4,
  },
  {
    fromCity: 'La Paz',
    toCity: 'Sucre',
    carrierId: 'copacabana',
    maxKg: 5,
    freightBob: 60,
    pickupBob: 15,
    hours: 12,
  },
  {
    fromCity: 'Santa Cruz',
    toCity: 'La Paz',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 50,
    pickupBob: 18,
    hours: 10,
  },
  {
    fromCity: 'Santa Cruz',
    toCity: 'Cochabamba',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 42,
    pickupBob: 18,
    hours: 8,
  },
  {
    fromCity: 'Cochabamba',
    toCity: 'Santa Cruz',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 42,
    pickupBob: 16,
    hours: 8,
  },
  {
    fromCity: 'Cochabamba',
    toCity: 'La Paz',
    carrierId: 'bolivar',
    maxKg: 5,
    freightBob: 40,
    pickupBob: 16,
    hours: 7,
  },
];

export const MANIFESTS: readonly Manifest[] = [
  {
    id: 'mf-1400',
    carrierId: 'bolivar',
    branchId: 'lp-terminal',
    departure: '14:00',
    plate: '3421 KZP',
    route: 'La Paz → Santa Cruz',
    sealed: 54,
    missing: 3,
    guias: ['TY-4471', 'TY-4470', 'TY-4481'],
  },
  {
    id: 'mf-1900',
    carrierId: 'bolivar',
    branchId: 'lp-terminal',
    departure: '19:00',
    plate: '2870 LFA',
    route: 'La Paz → Cochabamba',
    sealed: 39,
    missing: 1,
    guias: ['TY-4469'],
  },
];

const LANE: readonly { kind: Milestone['kind']; label: string; live: boolean }[] = [
  { kind: 'recogido', label: 'Recogido en tienda', live: true },
  { kind: 'sellado', label: 'Sellado en sucursal', live: true },
  { kind: 'manifiesto', label: 'Cargado al bus', live: true },
  { kind: 'en-ruta', label: 'En ruta', live: false },
  { kind: 'llegada', label: 'Listo para recoger', live: true },
  { kind: 'entregado', label: 'Entregado', live: true },
];

const ROUTE_NOTE =
  'Mientras viaja en bus no hay ubicación en vivo: te avisamos cuando llegue a la terminal.';

function milestones(
  reached: number,
  stamps: readonly string[],
  places: readonly string[],
): readonly Milestone[] {
  return LANE.map((step, index) => ({
    kind: step.kind,
    label: step.label,
    live: step.live,
    ...(index < reached ? { at: stamps[index], place: places[index] } : {}),
    ...(step.kind === 'en-ruta' ? { note: ROUTE_NOTE } : {}),
  }));
}

export const SHIPMENTS: readonly Shipment[] = [
  {
    guia: 'TY-4471',
    slug: 'ty-4471',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Rosa Villca', phone: '7712 4408', ci: '4408' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    content: 'Caja de ropa',
    weightKg: 3,
    carrierId: 'bolivar',
    departure: '14:00',
    pickupBob: 15,
    freightBob: 50,
    totalBob: 65,
    payer: 'remitente',
    paid: true,
    state: 'en-bus',
    createdAt: '2026-08-15T11:40:00',
    etaAt: '2026-08-15T21:40:00',
    pickupCode: '4471',
    driverId: 'd-marco',
    publicTracking: true,
    voucherPhoto: '/img/vouchers/ty-4471.webp',
    milestones: milestones(
      3,
      ['2026-08-15T12:05:00', '2026-08-15T14:22:00', '2026-08-15T14:00:00'],
      ['La Paz', 'Bolívar La Paz', 'Bus 3421 KZP'],
    ),
  },
  {
    guia: 'TY-4470',
    slug: 'ty-4470',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Marco Quisbert', phone: '7060 2211' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'cbba-terminal', city: 'Cochabamba' },
    content: 'Dos pares de zapatillas',
    weightKg: 2.5,
    carrierId: 'bolivar',
    departure: '19:00',
    pickupBob: 15,
    freightBob: 40,
    totalBob: 55,
    payer: 'remitente',
    paid: true,
    state: 'en-camino-a-sucursal',
    createdAt: '2026-08-15T12:20:00',
    etaAt: '2026-08-16T02:00:00',
    pickupCode: '4470',
    driverId: 'd-ivan',
    publicTracking: true,
    milestones: milestones(1, ['2026-08-15T13:10:00'], ['La Paz']),
  },
  {
    guia: 'TY-4468',
    slug: 'ty-4468',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Lucía Paz', phone: '7345 9080', ci: '9080' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    content: 'Caja de accesorios',
    weightKg: 1.8,
    carrierId: 'bolivar',
    departure: '22:30',
    pickupBob: 15,
    freightBob: 50,
    totalBob: 65,
    payer: 'remitente',
    paid: true,
    state: 'entregado',
    createdAt: '2026-08-13T09:00:00',
    etaAt: '2026-08-14T09:30:00',
    pickupCode: '4468',
    driverId: 'd-marco',
    publicTracking: true,
    milestones: milestones(
      6,
      [
        '2026-08-13T09:40:00',
        '2026-08-13T11:15:00',
        '2026-08-13T22:30:00',
        '2026-08-14T07:00:00',
        '2026-08-14T08:10:00',
        '2026-08-14T11:02:00',
      ],
      [
        'La Paz',
        'Bolívar La Paz',
        'Bus 2870 LFA',
        'Ruta La Paz → Santa Cruz',
        'Bolívar Bimodal',
        'Ventanilla 7',
      ],
    ),
  },
  {
    guia: 'TY-4473',
    slug: 'ty-4473',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Iván Rocha', phone: '7788 1200' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'oru-terminal', city: 'Oruro' },
    content: 'Caja de poleras',
    weightKg: 4,
    carrierId: 'illimani',
    departure: '16:30',
    pickupBob: 15,
    freightBob: 35,
    totalBob: 50,
    payer: 'remitente',
    paid: true,
    state: 'sin-conductor',
    createdAt: '2026-08-15T12:48:00',
    etaAt: '2026-08-15T21:00:00',
    pickupCode: '4473',
    publicTracking: true,
    milestones: milestones(0, [], []),
  },
  {
    guia: 'TY-4475',
    slug: 'ty-4475',
    importerSlug: 'tecno-import',
    recipient: { name: 'Carla Mendoza', phone: '7001 4455' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    content: 'Audífonos inalámbricos',
    weightKg: 0.6,
    carrierId: 'bolivar',
    departure: '19:00',
    pickupBob: 15,
    freightBob: 50,
    totalBob: 65,
    payer: 'destinatario',
    paid: false,
    state: 'esperando-recojo',
    createdAt: '2026-08-15T13:02:00',
    etaAt: '2026-08-16T05:00:00',
    pickupCode: '4475',
    publicTracking: true,
    milestones: milestones(0, [], []),
  },
  {
    guia: 'TY-4469',
    slug: 'ty-4469',
    importerSlug: 'tecno-import',
    recipient: { name: 'Pedro Luna', phone: '6712 3344' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'cbba-terminal', city: 'Cochabamba' },
    content: 'Cargador rápido',
    weightKg: 0.4,
    carrierId: 'bolivar',
    departure: '19:00',
    pickupBob: 15,
    freightBob: 40,
    totalBob: 55,
    payer: 'remitente',
    paid: true,
    state: 'recibido',
    createdAt: '2026-08-15T10:15:00',
    etaAt: '2026-08-16T02:00:00',
    pickupCode: '4469',
    driverId: 'd-ivan',
    publicTracking: true,
    milestones: milestones(1, ['2026-08-15T12:58:00'], ['La Paz']),
  },
  {
    guia: 'TY-4462',
    slug: 'ty-4462',
    importerSlug: 'belleza-import',
    recipient: { name: 'Andrea Suárez', phone: '7899 6543', ci: '6543' },
    origin: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    destination: { branchId: 'lp-terminal', city: 'La Paz' },
    content: 'Sérum y secador',
    weightKg: 2.2,
    carrierId: 'bolivar',
    departure: '22:30',
    pickupBob: 18,
    freightBob: 50,
    totalBob: 68,
    payer: 'destinatario',
    paid: false,
    state: 'listo-para-recoger',
    createdAt: '2026-08-14T15:00:00',
    etaAt: '2026-08-15T08:20:00',
    pickupCode: '4462',
    driverId: 'd-noemi',
    publicTracking: true,
    milestones: milestones(
      5,
      [
        '2026-08-14T15:40:00',
        '2026-08-14T17:05:00',
        '2026-08-14T22:30:00',
        '2026-08-15T06:00:00',
        '2026-08-15T08:20:00',
      ],
      [
        'Santa Cruz',
        'Bolívar Bimodal',
        'Bus 5512 HRT',
        'Ruta Santa Cruz → La Paz',
        'Bolívar Terminal La Paz',
      ],
    ),
  },
  {
    guia: 'TY-4459',
    slug: 'ty-4459',
    importerSlug: 'hogar-y-mas',
    recipient: { name: 'Julio Camacho', phone: '7233 8899', ci: '8899' },
    origin: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    destination: { branchId: 'cbba-terminal', city: 'Cochabamba' },
    content: 'Olla a presión',
    weightKg: 4.5,
    carrierId: 'bolivar',
    departure: '14:00',
    pickupBob: 18,
    freightBob: 42,
    totalBob: 60,
    payer: 'remitente',
    paid: true,
    state: 'entregado',
    createdAt: '2026-08-12T10:00:00',
    etaAt: '2026-08-12T23:00:00',
    pickupCode: '4459',
    driverId: 'd-noemi',
    publicTracking: false,
    milestones: milestones(
      6,
      [
        '2026-08-12T10:30:00',
        '2026-08-12T12:00:00',
        '2026-08-12T14:00:00',
        '2026-08-12T18:00:00',
        '2026-08-12T22:10:00',
        '2026-08-13T09:15:00',
      ],
      [
        'Santa Cruz',
        'Bolívar Bimodal',
        'Bus 9087 KKA',
        'Ruta Santa Cruz → Cochabamba',
        'Bolívar Cochabamba',
        'Ventanilla 2',
      ],
    ),
  },
  {
    guia: 'TY-4480',
    slug: 'ty-4480',
    importerSlug: 'moto-repuestos-bolivia',
    recipient: { name: 'Freddy Alanoca', phone: '7455 2020' },
    origin: { branchId: 'cbba-terminal', city: 'Cochabamba' },
    destination: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    content: 'Llanta 110/90-17',
    weightKg: 7,
    carrierId: 'bolivar',
    departure: '14:00',
    pickupBob: 16,
    freightBob: 42,
    totalBob: 58,
    payer: 'remitente',
    paid: true,
    state: 'incidencia',
    createdAt: '2026-08-15T08:30:00',
    etaAt: '2026-08-15T22:00:00',
    pickupCode: '4480',
    driverId: 'd-rene',
    publicTracking: true,
    milestones: milestones(1, ['2026-08-15T09:20:00'], ['Cochabamba']),
  },
  {
    guia: 'TY-4481',
    slug: 'ty-4481',
    importerSlug: 'deportes-andinos',
    recipient: { name: 'Mónica Ticona', phone: '7166 3311' },
    origin: { branchId: 'oru-terminal', city: 'Oruro' },
    destination: { branchId: 'lp-terminal', city: 'La Paz' },
    content: 'Mochila de montaña',
    weightKg: 1.9,
    carrierId: 'illimani',
    departure: '08:00',
    pickupBob: 15,
    freightBob: 35,
    totalBob: 50,
    payer: 'remitente',
    paid: true,
    state: 'en-bus',
    createdAt: '2026-08-15T06:40:00',
    etaAt: '2026-08-15T12:30:00',
    pickupCode: '4481',
    driverId: 'd-rene',
    publicTracking: true,
    milestones: milestones(
      3,
      ['2026-08-15T07:05:00', '2026-08-15T07:40:00', '2026-08-15T08:00:00'],
      ['Oruro', 'Illimani Oruro', 'Bus 7712 GGP'],
    ),
  },
  {
    guia: 'TY-4455',
    slug: 'ty-4455',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Sergio Vargas', phone: '7020 7788', ci: '7788' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'scz-bimodal', city: 'Santa Cruz' },
    content: 'Casaca de jean',
    weightKg: 1.2,
    carrierId: 'copacabana',
    departure: '20:00',
    pickupBob: 15,
    freightBob: 50,
    totalBob: 65,
    payer: 'remitente',
    paid: true,
    state: 'entregado',
    createdAt: '2026-08-10T17:00:00',
    etaAt: '2026-08-11T07:00:00',
    pickupCode: '4455',
    driverId: 'd-marco',
    publicTracking: true,
    milestones: milestones(
      6,
      [
        '2026-08-10T17:35:00',
        '2026-08-10T19:10:00',
        '2026-08-10T20:00:00',
        '2026-08-11T01:00:00',
        '2026-08-11T06:45:00',
        '2026-08-11T10:22:00',
      ],
      [
        'La Paz',
        'Bolívar La Paz',
        'Bus 4410 PLC',
        'Ruta La Paz → Santa Cruz',
        'Bolívar Bimodal',
        'Ventanilla 7',
      ],
    ),
  },
  {
    guia: 'TY-4483',
    slug: 'ty-4483',
    importerSlug: 'importadora-ale',
    recipient: { name: 'Ana Choque', phone: '7999 1010' },
    origin: { branchId: 'lp-terminal', city: 'La Paz' },
    destination: { branchId: 'cbba-terminal', city: 'Cochabamba' },
    content: 'Polera de algodón',
    weightKg: 0.8,
    carrierId: 'bolivar',
    departure: '22:30',
    pickupBob: 15,
    freightBob: 40,
    totalBob: 55,
    payer: 'remitente',
    paid: true,
    state: 'esperando-recojo',
    createdAt: '2026-08-15T13:20:00',
    etaAt: '2026-08-16T06:00:00',
    pickupCode: '4483',
    publicTracking: true,
    milestones: milestones(0, [], []),
  },
];
